### ISSUE TITLE
Output filename not --title as expected

### ISSUE THREAD

**Issue by windymilla** [gutenbergtools/ebookmaker#100]
When the HTML file in the attached [lamb.zip](https://github.com/gutenbergtools/ebookmaker/files/7534132/lamb.zip) is processed, the output filename is not as expected. Despite the command line containing the `--title` argument, some (incorrect) text from the source file was used for the output file name.

Command line and output:
```
$ tools/ebookmaker/ebookmaker.exe --verbose --config-dir=tools/ebookmaker --make=epub.images --output-dir=/c/DP/a --title=sample_ebook  /c/dp/a/lamb.htm
WARNING:root:No gnu dbm support found. Rhyming dictionary not used.
INFO:root:Running html thru tidy.
INFO:root:tidy: Doctype given is "-//W3C//DTD XHTML 1.0 Strict//EN"
INFO:root:tidy: Document content looks like XHTML 1.0 Strict
INFO:root:no language found, using default
2021-11-14 16:15:02,091 INFO      #0     Creating Epub file: C:\DP\a\96-images-epub.epub
2021-11-14 16:15:02,100 INFO      #0     Done Epub file: C:\DP\a\96-images-epub.epub
2021-11-14 16:15:02,104 INFO      #0      epub.images made in 0:00:00.228050
```

The output filename `96-images-epub.epub` was used instead of the expected `sample_ebook-images-epub.epub` as given by the `--title` argument.

Inspecting the source file (stripped from a real example), it can be seen that line 18 is
`96, High Street Oxford</p>`
Removing the `96` from this line causes the expected output name `sample_ebook-images-epub.epub` to be used.

I would expect the command line option to override any attempts to extract a title from the HTML source.

**Comment by eshellman** [comment]
I'm thinking that we need to stop using the title for filenames. The title is being used in many places, including header metadata. We currently have a command line parameter --output-file which can be used to set the name of the output file.  The title will often be an invalid name for a file. But changing the behavior may surprise people.

There's separately the issue of whether to override the title extracted from metadata with a cli-supplied title. I worry that changing the current behavior will be perceived as a bug by users who expect a title to be picked up from metadata.

The metadata parser thinks that 96 is the Gutenberg ebook id.

So I think changing that behavior may do more harm than good.

It's easier to enhance --output-file if that's needed than to mess with the already overloaded --title  or we can add an argument --name that will work like you want --title to work, but without messing with the title.

so I'm labeling this as a feature request.

**Comment by windymilla** [comment]
I tried using --output-file, but that does not work if you are trying to generate the epub and mobi versions in one run, since they need two different output filenames. 
I could make the Guiguts code run ebookmaker twice, once for the epub and once for the mobi, though that will take twice as long. In that case, ebookmaker would not need a code change.
Alternatively, I could make Guiguts have two separate menu options, one to create the epub, and a second to create the mobi, though that again is less efficient for the user.
Or, you could add a --name option to ebookmaker. I can't release Guiguts with this change in behaviour - users will expect the name to be predictable, either based on their input filename, or based on the book title, but not a random number extracted from the text. 
Do you think a version with a --name option could be created fairly quickly, or if you would prefer not to, or think it will be a long time, I will choose one of the "run twice" options mentioned above.
Thanks

**Comment by windymilla** [comment]
Update - I tried running ebookmaker twice, once with --make=epub.images, and once with --make=kindle.images and using the output-file to specify the two filenames. However, it seems (unless I've done something wrong) that if you specify output-file, you always get an epub, not a mobi, even if you just specify --make=kindle.images. So my attempt to run the code twice has failed. Any thoughts?  Thanks

**Comment by eshellman** [comment]
ok, that's a bug!
