### ISSUE TITLE
Cover image styling

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#104]
Cover images are styled with `max-width:100%`, which makes sure a too-large image will be constrained to the ebook's screen. Images that are smaller than the screen resolution do not fill the screen. A `width:100%` might be all that it takes.

Background: my Kobo has a screen resolution of 1448x1072. A test of 100 recent ebooks shows only 19 of those have a cover image that will fill the screen on the ereader. As an example, the cover for ebook 66071 fills up less than 25% of the screen.

**Comment by eshellman** [comment]
It probably makes sense to see if there's smarter css  we can develop for EPUB3. 
 - covers will look terrible if expanded too much.
 - not sure if we want to use width=100% if the cover has a taller aspect ratio than a screen, or if the screen is used in landscape view.

**Comment by asylumcs** [comment]
On Wed, Dec 29, 2021, at 9:10 AM, Eric Hellman wrote:
> It probably makes sense to see if there's smarter css we can develop for EPUB3.
> 
>  * covers will look terrible if expanded too much.

Some covers will look bad if expanded. Seems we shouldn't design for the edge cases. If we leave it alone we get this:



>  * not sure if we want to use width=100% if the cover has a taller aspect ratio than a screen, or if the screen is used in landscape view.

Again, *most* covers have a similar aspect ratio. What you have now doesn't protect against a too-tall cover. You only limit max-width and you don't use a viewport (for 100vh). We have no perfect solution unless we control the cover image and we don't. The guidelines on cover images are not go/no-go. So we need the best solution for the typical--not every--cover. We don't have it now unless we want to deliver epubs to the end user that look like we don't know what we are doing.

My thoughts only. Your decision.  --Roger

**Comment by gbnewby** [comment]
(If there are epub3 features that can help, that might be desirable in the future.

Today, we've got a lot of epub2, and we might keep using that format in the future for some titles that cannot yield suitable HTML5.)

For our current epub2 eBooks, my inclination would be to stretch or squeeze the images to width=100 and height=100. That will often change the aspect ratio, but seems like a better brute-force solution than the current situation.

I like the constraint of max-width=100% but that serves only to squeeze, not stretch. A full-screen image is what people expect...

**Comment by asylumcs** [comment]
One other data point. I believe the current industry standard for minimum cover image size is 1600x2560 pixels or larger. That's for epub and Kindle. We've told DP that covers should be "at least 650x1000." That's what's in their PPV guidelines. If we asked for and accepted 1600x2560, the concern about images degrading by being stretched would be mollified. Of course we could not require it because sometimes the PPer is working from harvested images where they can't control the resolution. But we should allow it. My 2¢.

**Comment by gbnewby** [comment]
Following up, after some experimentation: This is some CSS that would seem to work well: "margin:auto; max-height:100%; max-width:100%"

It doesn't seem to be specific to epub2 or epub3, it's just generic CSS.
