### ISSUE TITLE
Data-ssml-* attributes

### ISSUE THREAD

**Issue by michael-roe** [gutenbergtools/ebookmaker#108]
The v12 branch has support for turning data-ePub-* attributes into ePub: attributes in epub3. It would be useful if it did something similar for data-ssml-* attributes, as the ssml namespace is also in the epub3 spec.

**Comment by eshellman** [comment]
http://kb.daisy.org/publishing/docs/text-to-speech/ssml.html says "There is no support for the EPUB SSML attributes in reading systems at this time." 

Do you have a use case?

**Comment by michael-roe** [comment]
The main use case I had in mind was books where the author has created a new word by Anglicising a foreign term, resulting in a word that is neither in English pronunciation dictionaries (because it isn't actually English) and isn't in pronunciation dictionaries for the source language either, because its spelling and pronunciation were changed by being Anglicized.

An unmodified foreign word you could just tag with xml:lang, but here you have a word that is not quite in either language, and you need to help out text to speech by specifying how it's supposed to be pronounced.

**Comment by eshellman** [comment]
How would you test an implementation? XHTML5 submissions are free to include `data-` attributes (which get stripped in EPUB2), but converting these into namespaced attributes for EPUB3 would require testing to make sure nothing downstream chokes on them. And without a reader that supports the attributes, there's no way to check that an implementation is correct.

**Comment by michael-roe** [comment]
We have something if a chicken-or-egg problem here, in that the implementors of reading systems also have a problem testing the feature if ebook creating software can't create books that use it.

hmmm... I am not sure what the best way forward is here.

**Comment by michael-roe** [comment]
Maybe using the epub3 ssml namespace isn't the right way to do this.

**Comment by eshellman** [comment]
closing as a won't fix
