### ISSUE TITLE
unnecessary recompression

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#109]
Ebookmaker is recompressing images whether they need it or not. Specifically line 110 of ImageParser.py appears to be executing every time. I suspect the problem is in the way get_image_data handles a request for image size with no quality specified. That causes line 109 to always evaluate as True to enter the recompression loop.

Here's more detail of what happens. A jpeg image is processed  having quality 35 by ebookmaker. Though it shouldn't, it executes the "find best quality that fits into max size" loop. The image is resampled at each of these quality settings, in order: (90, 85, 80, 70, 60, 50, 40, 30) and it stops at 30, which is less than the starting 35. It's now a different image: different file size, different quality, different sampling factor (sRGB goes from 1x1,1x1,1x1 to 2x1,1x1,1x1) and slightly different colors (less red and green, more blue in my testing.) The goal is to not recompress a file that the submitter has provided that is already under MAX_IMAGE_SIZE (approx. 256Kb).

**Comment by eshellman** [comment]
I'm unable to reproduce the "Always Recompress" behavior.

**Comment by eshellman** [comment]
I confirm that the color table and profile changes in the EPUB, but the compression loop is not executed if compression is not needed.
