### ISSUE TITLE
Left-hand notes not handled well

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#110]
Per a reader report, this eBook has notes on the left-hand side that are not represented well in the epub: https://www.gutenberg.org/ebooks/33849

It's not obvious to me how this should be handled, but the way it's being handled now results in mangled display in the epub.

**Comment by eshellman** [comment]
epub3 version looks good (change extension to epub to view)
[33849-images-epub3.zip](https://github.com/gutenbergtools/ebookmaker/files/9357801/33849-images-epub3.zip)
.
