### ISSUE TITLE
Enhancement request: allow the ".xhtml" extension

### ISSUE THREAD

**Issue by rtonsing** [gutenbergtools/ebookmaker#119]
I like using it during PP because it causes the browsers to report major syntax issues, helping to catch them earlier in the process.

**Comment by eshellman** [comment]
what makes you think the .xhtml extension is not allowed by ebookmaker? seem to work just fine for me.

**Comment by rtonsing** [comment]
Sorry, but we could not identify a file ending in rst, txt, htm, or html. Follow this link to see what was identified. You might need to give a more Unix-friendly filename (no spaces, lower case, no special characters). Please try again, or send email if you need help or things seem amiss.

    https://ebookmaker2.pglaf.org/cache/20220928081110

This is eBookmaker version 0.12.13. It fails with both zipped & direct .xhtml upload. Maybe it is the web site & not the app?

**Comment by gbnewby** [comment]
I'll fix this at soonest opportunity. It's just an issue with the filename matching within the wrapper script that runs ebookmaker.

The bottom of every page in the online ebookmaker says who to contact for support, and doesn't mention using github.
