### ISSUE TITLE
ebookmaker displays HTML comments when viewing its .epub/.epub3 files in an epub reader

### ISSUE THREAD

**Issue by G4OEU** [gutenbergtools/ebookmaker#120]
Comments in HTML that are bracketed by  are not displayed in a browser but are displayed in an epub reader (Calibre) when viewing .epub/.epub3 files generated by ebookmaker. I am using the ebookmaker included with the beta version of Guiguts 1.5.0.

I am unable at present to view MOBI files but assume the issue is seen there as well.

The attached file demonstrates the problem.

[ebookmaker-bug-report.txt](https://github.com/gutenbergtools/ebookmaker/files/9669150/ebookmaker-bug-report.txt)

**Comment by eshellman** [comment]
I was wrong - it's a garden-variety bug. Thanks!
