### ISSUE TITLE
EPUBs use UTF-8 non-breaking spaces instead of entities

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#127]
Ebookmaker appears to convert non-breaking space numeric or named entities to the UTF-8 codepoint. Sigil's implementation converts all representations of the non-breaking space to the numeric entity of \&#160;. It appears to only do this conversion to a numeric entity for the non-breaking space, as if there is a particular reason for it. I can't find guidance on this in the EPUB3 specs.

**Comment by eshellman** [comment]
these are equivalent. I can't think of any reason it should matter.
