### ISSUE TITLE
Epub3 file reports author as "Unknown" in Calibre

### ISSUE THREAD

**Issue by rtonsing** [gutenbergtools/ebookmaker#128]
The Epub2 file generated at the same time shows OK
The opf file has:
`    <dc:creator id="author_0">First Last</dc:creator>
    <dc:creator id="id-2">Unknown</dc:creator>
`
maybe the 2nd entry causes the issue.
Using the web site, version 0.12.14.

**Comment by rtonsing** [comment]
The web site says version 0.12.14, but the report says 0.12.13.

**Comment by eshellman** [comment]
did you use online ebookmaker and leave the author input blank? I thing what's going on is that the web script is defaulting that input with "unknown" and ebookmaker sees that as well as the author in the metadata header. Not sure what the right thing to do is.

**Comment by rtonsing** [comment]
Except that epub2 got the info. But it doesn't seem to happen anymore.
