### ISSUE TITLE
Cover image issue in EPUB3 only

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#129]
The same file was used to generate an EPUB and an EPUB3. I first noticed that there was no icon for the downloaded EPUB3 but there was for the EPUB. When I loaded both files onto a physical Ebook reader (Kobo), I got a proper bookshelf icon for the EPUB but a very different and incorrect one for the EPUB3. Screenshot from my phone is attached. The top image is the EPUB; the bottom one is the EPUB3, where it looks like max-width or max-height or both are not in play. The top image is what I expected for both.
![IMG_1137](https://user-images.githubusercontent.com/37535965/193471802-4511f783-2bc3-4371-96d4-3e189cf5de4f.jpg)

**Comment by eshellman** [comment]
It seems we have to use the epub2 method to declare the cover image. I can't test on kobo, but something similar happens on MacOS
