### ISSUE TITLE
EPUB3 cover image cropped display

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#132]
In 0.12.16, the cover image in the EPUB3 is not scaled or centered on a physical Ereader. See the left image in the picture below.

Replacing the generated code in wrap0000.html with this works beautifully:

```
<?xml version="1.0"?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>"Cover"</title>
    <link href="pgepub.css" rel="stylesheet"/>
  </head>
<body class="fullpage">
  <div class="cover" id="cover">
    <svg xmlns="http://www.w3.org/2000/svg" height="100%" preserveAspectRatio="xMidYMid meet" version="1.1" viewBox="0 0 1726 2560" width="100%" xmlns:xlink="http://www.w3.org/1999/xlink">
      <image id="coverimage" alt="cover image" width="1726" height="2560" xlink:href="3709865464861500397_cover.jpg"/>
    </svg>
  </div>
</body>
</html>
```
and the CSS that goes with it:
```
   .cover{
      background-color: grey;
      text-align: center;
      padding: 0pt;
      margin: 0pt;
      page-break-after: always;
      text-indent: 0;
      width: 100%;
      height: 100%;
    }

    body.fullpage {
       margin: 0;
       padding: 0;
    }
```
My source for this code was here:
[](https://ebooks.stackexchange.com/questions/1186/how-do-i-add-a-cover
-and-other-pictures-to-my-epub
)

The advantage, is that .SVG files have a little size, and resize very well, without losing clarity. The goal is to have the cover automatically resizing according to the reader screen, that can be very different from one reader to another. This works well for me on both my new Kobo EPUB3 reader and an ancient Nook (BNTV400).

Image on the left is as generated by ebookmaker 0.12.16 (on my Kobo). Image on right is with my suggested code (on a very old Nook).

![for-github](https://user-images.githubusercontent.com/37535965/193973923-7080d7b9-b916-4e99-b71e-fcb729ab1e00.jpg)

**Comment by eshellman** [comment]
IIRC we used media queries to get the right cover size in EPUB3. Maybe they got lost, or mayber the KOBO doesn't support Media Queries? How old is it?

**Comment by eshellman** [comment]
Seems worth a try!

**Comment by asylumcs** [comment]
Happy to test it on a physical Ereader. EPUB or EPUB3 readers are available.

**Comment by eshellman** [comment]
could you try the same file but removing `width="1726" height="2560"` in the svg?

**Comment by asylumcs** [comment]
yes I can try that. Those were the actual dimensions of the image. I'll find out if that's an important part of the recipe by (1) leaving it out (your request) and (2) using a different-sized cover.

**Comment by asylumcs** [comment]
Here are my test results.
(1) if I have the width and height specified, the cover image is correct using the EPUB3 when viewed on a KOBO (EPUB3 reader) and my Nook (EPUB2).
(2) if I drop the width and height specification, the cover image is still correct on the KOBO but is only a fraction of the screen on the Nook.
I tried this with two different books. Conclusion: the Nook needs the dimensions specified.
Hope this helps. Need different testing--just ask.

**Comment by eshellman** [comment]
thanks. some extra work to try that, so not this release

**Comment by eshellman** [comment]
@asylumcs if your epub3 file passes epubcheck, could you post it here? or if you have an epub3 file with a similar svg cover that passes epubcheck? My first attempt fails.

**Comment by asylumcs** [comment]
[pglaf.org/~rfrank/tmp/esh-epub3.epub](url)

`$ epubcheck esh-epub3.epub 
Validating using EPUB version 3.2 rules.
No errors or warnings detected.
Messages: 0 fatals / 0 errors / 0 warnings / 0 infos`

**Comment by eshellman** [comment]
try this one:
[27203-images-epub3.epub.zip](https://github.com/gutenbergtools/ebookmaker/files/9874283/27203-images-epub3.epub.zip)

**Comment by asylumcs** [comment]
![kobo](https://user-images.githubusercontent.com/37535965/198180437-55bfb793-a31c-4c63-b520-fe4042fbfd63.jpg)
![nook](https://user-images.githubusercontent.com/37535965/198180456-dfa87410-f662-4c25-8c24-23c59b7f67cf.jpg)

**Comment by asylumcs** [comment]
first one is Kobo. second is Nook.

**Comment by asylumcs** [comment]
I think you were most concerned about the cover image and I've shown you how they appear. In case you actually wanted further analysis, here are the things that Sigil didn't like about the epub. These may well be just the style of the Sigil designers. Or they may feel the changes are important in some situation or for some target device. I don't know. But here's the list:

- they change self-closing tags to separate tags. `<a id="id_1"/>` becomes `<a id="id_1"></a>`
- same for all others, such as `<pre/>`
- they change literal hard spaces to `&#160;` No other characters were seen to be changed to their numeric entity
- they include `<!DOCTYPE html>` after the `<?xml ...>` first line.
- they use double quotes in the `<?xml version="1.0" encoding="utf-8"?>` line.
- they add a second namespace to the `<html ...>` line: `"xmlns:epub="http://www.idpf.org/2007/ops"`

Again, these may be specious. Or they may mean something. Up to you. Nice work on the cover images.
