### ISSUE TITLE
PG header is not followed by page break in EPUB2

### ISSUE THREAD

**Issue by windymilla** [gutenbergtools/ebookmaker#138]
In the EPUB3 version, the `section.pgheader` is set to do `page-break-after: always` so there is a page break before the start of the actual book (usually the title page)
However in the EPUB2 version, a `div class="pgheader"` is used. There is no `div.pgheader` in the CSS to force the page break. 

This means that all EPUB2 versions start their title page part way down a physical page and end up with a page break across the middle of their title page.

 See attached EPUB2 and EPUB3 examples converted with 0.12.19
[10001-images-epub.zip](https://github.com/gutenbergtools/ebookmaker/files/9833536/10001-images-epub.zip)

**Comment by eshellman** [comment]
Is this a new behavior or has this always been so?

**Comment by windymilla** [comment]
I don't recall seeing it before, but that is because I normally see epubs before they are posted. Now ebookmaker adds the PG header and I see it with the header before it's posted. Sorry. No way for me to be sure what it used to do.
