### ISSUE TITLE
Missing space in epub ToC for multi-line chapter headings

### ISSUE THREAD

**Issue by windymilla** [gutenbergtools/ebookmaker#141]
The following construction is commonly used when a chapter begins with the chapter number on one line and the chapter title on the line below:
```
<div class="chapter">
<h2 class="nobreak" id="I">I<br>THE UPPER DANUBE</h2>
</div>
```
Note that the chapter number `I` is separated from the title `THE UPPER DANUBE` by a `<br>` element to give this effect
```
        I
THE UPPER DANUBE
```

In the generated ToC in the epub file, the chapter appears as `ITHE UPPER DANUBE` with no space separating the number from the title.

Previous versions of ebookmaker used to replace the `<br>` with a space to give `I THE UPPER DANUBE` which is much more readable. 

I don't know exactly when the change happened - I tested ebookmaker 0.11.30, which works OK, and 0.12.20 which doesn't.

**Comment by windymilla** [comment]
Should have mentioned - it applies to the h3 headings as well, of course

**Comment by eshellman** [comment]
I think this was something tidy did - it normalized whitespace in a way that a lot of people objected to, but in this case, people seem to have relied on its behavior. Why the "nobreak" class?

Why don't people add the whitespace?

I can change the behavior but it will be ugly

**Comment by eshellman** [comment]
This problem will also show up in plain text versions derived from html.
I really hate this. Is there anything else like this that people do??

**Comment by eshellman** [comment]
Lord help us if anyone puts dropcaps in headers

**Comment by windymilla** [comment]
> could you point to a book where this happens?

#68492, Chapter II only

**Comment by windymilla** [comment]
> This problem could also show up in plain text versions derived from html. But it seems Ebookmaker only does that for rst source. I really hate this. Is there anything else like this that people do??

Surely when converting to plain text ,the `<br>` would be converted to a line break (which is what is wanted), so you'd get something like
```
I
THE DANUBE
```

That is how it looks in the original book - the chapter number on one line, and the chapter title on the line below.

If I wrote `This<br>is<br>a<sentence.` in HTML, I wouldn't expect `Thisisasentence` to come out of any processor.

**Comment by windymilla** [comment]
I thought the problem would occur more frequently. However, it all works fine if the PPer puts
```
<h2>CHAPTER I<br>
THE DANUBE</h2>
```
which is more common.

**Comment by windymilla** [comment]
> Why the "nobreak" class?
The "nobreak" is very commonly used. The problem is that ebookmaker forces a pagebreak at h2. However, you often don't want the page break exactly there. There may be a page number or a decorative heading before the h2. Since you require a "chapter" classed div to ensure chunk breaks happen at sensible places, which forces a page break, you don't want another page break to happen at the h2. So, the "standard" practice at DP is to use something like
```
<div class="chapter">
<span class="pagenum">...[27]...</span>
<h2 class="nobreak">Chapter 2</h2>
</div>
```
You have to use a class (rather than just saying saying no pagebreaks on h2s) because the ebookmaker h2 override comes after the users CSS. So the class makes it more specific, hence allowing override.

**Comment by eshellman** [comment]
It's not entirely correct that `br` is whitespace because you can apply `display:none` to it. Thanks for clarification of the nobreak class.

**Comment by windymilla** [comment]
Fair enough (though you're asking for trouble if you do IMHO)

Do you think ebookmaker's behaviour should stay as it is then?
I suppose a warning could be added to PPer documentation at DP to try to avoid it happening again.

**Comment by eshellman** [comment]
I'm adding the whitespace - I can't think of any way it can hurt. Whether I like it is not really relevant. What I hate is having to try to think of ways it could go wrong.

**Comment by windymilla** [comment]
Thanks Eric. Hopefully the fact that it used to do that means that there aren't too many ways for it to go wrong (fingers crossed)
