### ISSUE TITLE
HTML chunking behavior

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#142]
Line 216 of HTMLChunker.py will generate a new page in epub only if at least 1000 bytes are in the chunk as hard-coded in lines 34 and 82. There are legitimate situations in an ebook where a new page is desired where the chunk has fewer that 1000 bytes. A copyright page is an example. What users are forced to do is to put in a dummy comment of at least 1000 bytes to get the page break they want. That puts something like this in the HTML:
```
<div class="section">
<hr class="divider2 x-ebookmaker-drop">
<p class="center">COPYRIGHT, 1915, BY CLARISSA A. KNEELAND</p>
<p class="center">ALL RIGHTS RESERVED</p>
<p class="center"><em>Published October 1915</em></p>
</div>

<!-- 
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz -->
```
Seems to me we don't want users to have to do that to get a page break in their EPUB. There should be a way in their HTML to get a page break where desired without adding a huge, useless, and confusing comment block. (For reference: Sigil provides user-generated EPUB page breaks with a one-line HTML comment with a particular phrase in it).

**Comment by jj2017** [comment]
I would really appreciate a means to handle the page breaks for small chunks efficiently and elegantly. A one liner to handle such situations sounds excellent.

**Comment by eshellman** [comment]
same as #138. use `page-break:after` in the css. A fix is in  f4fd31a0d79e19d76c8ca0e7faa800590c14bb55 which should be deployed this week

**Comment by asylumcs** [comment]
Using the suggested `page-break:after` (which I'll code as `page-break-after:always`) is not a solution to this issue. Using CSS for a page break only works for those devices that recognize and honor the page-break CSS. Some devices do; many do not.
This issue is about the behavior of the HTML chunker. A new chunk is a new page by virtue of it creating a separate xhtml file inside the EPUB. What is needed is a way for the user to trigger a new chunk without having to include at least 1000 characters in a comment.
Right now a new chunk may be triggered by any of these keywords: `div.section`, `div.chapter`, `section`, `h1`, `div`, `h2`, `h3`, `p`, or `figure`. A new chunk is conditional based on how much text is already in the chunk. The minimum amount of text right now is approximately 1000 characters. One fix for this issue is to have an additional trigger on, for example, `div.ebookpage` that has no minimum content. That would mean the 1000 characters of comment would not be needed. A `div.ebookpage` would simply close out and emit a chunk (as a new xhtml file in the EPUB). That should result in a physical page break in all devices and readers.

**Comment by jj2017** [comment]
Roger's explanation is better than anything I could say. There is reference to the issue here:
https://www.jutoh.com/kb/html/section-0435.html
We need a way of telling ebookmaker to make a new section regardless of size.

**Comment by eshellman** [comment]
> Some readers, such as Adobe Digital Editions 4 (Epub 3 only), Calibre, and AZARDI do not honour forced page breaks, although all Epub readers do interpret a new section as a page break.

Does this mean that ADE is the main problem? I think it's still written in COBOL :wink:

**Comment by jj2017** [comment]
EPUB2 works as expected; it is only EPUB3. 

I agree that dummy text is not elegant or efficient, but sometimes needs must.

A div instead of comment will do that same job, at the moment. Why would it be deliberately removed when there is an express request to leave it in place? 

Is there no way to future proof construction such that when a break is really important there will be something ebookmaker will recognise as meaning "break here no matter what else". Perhaps something like .x-ebookmaker-3 important or some such.

I have no other target software to use to check EPUB3s. What should we be using?

**Comment by asylumcs** [comment]
Chunking will cause a page break for all known readers and apps. Forcing a chunk is one solution but after further study of the EPUB3 spec, it doesn't look like the best solution. For those devices that implement the page-break capabilities in the spec, we don't need to force a chunk.
If we are going to code to the EPUB3 spec and not to a few non-conforming devices, which seems reasonable, then this issue should be closed without further action.

**Comment by jj2017** [comment]
Okay, I give up. Thanks, and sorry for wasting everyone's time.

**Comment by jj2017** [comment]
<section></section> doesn't do the job either for ADE, or at least not that I could get to work. It is the chunking size that causes the problem--the chunk needs to allow for a smaller amount of content.
