### ISSUE TITLE
Always honor page-break requests, regardless of text length

### ISSUE THREAD

**Issue by charliehoward4dp** [gutenbergtools/ebookmaker#147]
The Front Matter of most books contains several short segments, each of which is printed on a new page.  An example of this is a Copyright notice.  Rather than placing a minimum length on what qualifies as a "chapter" for page-break purposes, please honor page-break requests even when there are only a few characters involved.

**Comment by jj2017** [comment]
This is the same issue as #142 which has been closed. I would very much like to see something done to overcome this problem. The front matter of some of our ebooks are looking like a scrambled mess.

**Comment by eshellman** [comment]
could you please point to a specific book so I can see what the issue is?

**Comment by eshellman** [comment]
Also please specify what reading environment and which version of EPUB you are asking about. For example, we can't tailor our EPUB3 files for ereaders such as ADE with horrible EPUB3 implementations.

**Comment by eshellman** [comment]
As a reminder,  Ebookmaker tries its hardest to put hard page breaks after
'div.section', 'div.chapter',  and  'section'  section elements. It never adds hard page breaks inside 'table', 'figure', 'dl', 'ol', or 'ul' elements.

**Comment by charliehoward4dp** [comment]
For an example of the new-page problem, please try using the epub3 version of "Seven Years in Vienna", which is [HERE](https://www.pgdp.net/c/project.php?id=projectID5ebde56b8dd79) in DP's Smooth-reading pool. Use it with the Kindle for IOS app.

**EXPLANATION OF WHY THIS MATTERS**
For me, a fundamental obstacle in testing the epub versions is the time and effort needed to upload them to a website, then download them to my reading device (an iphone, these days ... my Android devices no longer work and my Kindle broke recently), and then, for Kindle, to use Send to Kindle to upload them yet again, this time to Amazon, and then wait for Amazon to download them yet again to the Kindle for IOS app.  With the other ereaders on my phone, the effort is "just" uploading to a website and then downloading (once) to my phone. From there, the epubs can be opened in several apps.

If errors are found (almost always), the entire process, must be repeated.  This is excessive effort, IMO, so I do as much testing as possible on my computer before running the [hopefully] final tests as described above.

By contrast, testing on my Windows computer is trivial: just open the epub2 or epub3 in an available ereader. The limitation here is that I only have three ereaders (that I can trust for security) on my computer: Kindle for PC (the test file works properly on it, but since the test file doesn't work properly on my phone, that's a useless test), Calibre (works fine, but I don't think Calibre is widely used on handheld devices), and ADE (which, as you said, is not implemented perfectly).

**Comment by eshellman** [comment]
looking at this example, I'm guessing that you want a hard break after "printed in great britain". So why not just put the title page, up to "printed in great britain"  in a section element?

**Comment by charliehoward4dp** [comment]
Just tried that, but there was an "issue" and even after working around it, the epub3 still didn't work with Kindle for IOS.  (Many of our ebooks do not work properly with that app, but it's rather widely-used, and doesn't require anyone with an IOS device to purchase a separate ereader device.)

The issue is that `<section>` apparently needs to be followed by a heading tag, e.g., `<h2>`. The title page doesn't have a heading in that sense, so the NU HTML Checker issues a warning about it.  My workaround was to put an acceptable dummy heading after the `<section>` tag: `<h2> </h2>`, with a hard space between the opening and closing tags.  That satisfied the Checker, but in the Kindle for IOS app, the generated epub3 still placed the Frontispiece on the same page as the `<h1>` heading and the  "Printed in Great Britain" on the same page as the title page.

Further update: In addition to the other ereader apps I've tried, I just tried Kobo, both for Windows and for IOS.  The Windows version won't accept epubs from my own computer, but [apparently] only from the Kobo bookstore.  The IOS version accepted the epub3 that uses `<section>`, but ignored `<section>` even more often than did Kindle for IOS.

So far, the only IOS ereader apps I've tested that honor `<section>` are iBooks and Nook, and fortunately, both of them are widely-used.

Ignoring the unsupported-by-PG ADE, the only Windows apps with which I feasibly can test are Kindle for PC (which gives different results than does Kindle for IOS) and Calibre (which, while an excellent ereader, does not appear to be as popular as the big commercial brands).

Obviously, I can't know what a real Kindle or real Kobo will do, but one by one, I'm finding that some of the most popular epub readers will not display our ebooks properly.  Ignoring this is like trying to fight City Hall.

**Comment by eshellman** [comment]
Did <div class="section"> work?

We can report the Kobo/windows problem as a bug if you can write a proper bug report. is it only epub3 or epub2 as well? Do the EPUBs pass Epubcheck? What OS version, etc. I know the Kobo people and I'm pretty sure they would fix it.

The Epub -> kindle thing is still unstable; we can worry about it in a year. If Kobo gets fixed and send-to-kindle doesn't, we can productively fight city hall.

**Comment by charliehoward4dp** [comment]
> Did `<div class="section">` work?

That's not what I tried, and I don't know the css definition to use for "section". (All the examples I could find use the HTML tag.) All I did was to place `<section>` where a page break should occur, and `</section>` at the end of the block. This was not done the way I'd like, as there normally would not be `<h2>`'s in those positions.

How should the proper bug report be written?

rfrank tested the new version (with `<section>`) on a real Kobo and his results were worse than the ones on the Kobo for IOS app: ignored page breaks, errors in the ToC and LoI, problems with captions. (He has the details, but I dont.)  That version wouldn't even download into his real Nook, whereas it worked fine in the Nook for IOS app (honored page breaks, ToC and LoI fine).

All of the updated materials for the new version are in the Smooth-reading pool at DP, at the same link as shown above: [HERE](https://www.pgdp.net/c/project.php?id=projectID5ebde56b8dd79).

**Comment by jj2017** [comment]
I thought it is recommended that we don't use class names the same as recognised html5 elements, section being one of them.

Having said that, I've been using <div class="section"> and <div class="chapter"> for as long as we've been asked to use <div class="chapter"> as I thought ebookmaker was supposed to force a break for both, but if the chunk is not large enough neither forces a page break in epub3.

As Charlie says, <section> usually requires a heading H1-H6. The spec says "A section, in this context, is a thematic grouping of content, typically with a heading."
https://www.w3.org/TR/2011/WD-html5-20110525/sections.html#the-section-element

From what we've seen and discussed so far, it seems the only way to satisfy those of us who are concerned that our books aren't looking the best they can be is to have a smaller minimum chunk size. Otherwise the temptation is great to add a comment with dummy text to pad it out--except Eric has said he might be planning to remove html comments (which I think is not a good idea because the submitter of the book would not have used comments unless they thought they were needed/helpful).

**Comment by charliehoward4dp** [comment]
The padding approach didn’t work for me: I tried a 1K paragraph of hard spaces mixed with occasional regular spaces and newlines. It wasn’t a comment, but visible text (well, just spaces that added a few lines in HTML), within the `<section>`, but it didn’t force a page break in the three epub readers that weren’t honoring page-break-after.

**Comment by jj2017** [comment]
I used actual alphabetical letters.

**Comment by eshellman** [comment]
> On Dec 21, 2022, at 2:06 PM, Charlie Howard ***@***.***> wrote:
> 
> 
> Did <div class="section"> work?
> 
> That's not what I tried, and I don't know the css definition to use for "section". (All the examples I could find use the HTML tag.) All I did was to place <section> where a page break should occur, and </section> at the end of the block. This was not done the way I'd like, as there normally would not be <h2>'s in those positions.
> 
The chunker should always break the page AFTER the section, not before.

<div class="section"> should work the same way.

Ebookmaker has worked this way for probably ten years, I guess no one ever documented the behavior.
> How should the proper bug report be written?
> 
> rfrank tested the new version (with <section>) on a real Kobo and his results were worse than the ones on the Kobo for IOS app: ignored page breaks, errors in the ToC and LoI, problems with captions. (He has the details, but I dont.) That version wouldn't even download into his real Nook, whereas it worked fine in the Nook for IOS app (honored page breaks, ToC and LoI fine).
> 
> All of the updated materials for the new version are in the Smooth-reading pool at DP, at the same link as shown above: HERE <https://www.pgdp.net/c/project.php?id=projectID5ebde56b8dd79>.
> 

A bug report includes sample files, description of how to reproduce the problem, a description of the expected result, and a description of how the problem result differes from the expected result.
Software version numbers, Operating system and version numbers are also needed.

**Comment by charliehoward4dp** [comment]
I'm way out of my depth with this, so I'll drop the request.

**Comment by eshellman** [comment]
> On Dec 21, 2022, at 6:55 PM, jj2017 ***@***.***> wrote:
> 
> 
> I thought it is recommended that we don't use class names the same as recognised html5 elements, section being one of them.
> 
> 

Ebookmaker translates <section> to <div class="section" for use in EPUB2, so there's the risk you will inadvertently have "section" handling applied to some tags where you don't want it. But here you want it.
> Having said that, I've been using
> 
> and
> for as long as we've been asked to use
> as I thought ebookmaker was supposed to force a break for both, but if the chunk is not large enough neither forces a page break in epub3.

can't see what you entered.

> 
> As Charlie says,
> 
> usually requires a heading H1-H6. The spec says "A section, in this context, is a thematic grouping of content, typically with a heading."
> https://www.w3.org/TR/2011/WD-html5-20110525/sections.html#the-section-element <https://www.w3.org/TR/2011/WD-html5-20110525/sections.html#the-section-element>
> 
> From what we've seen and discussed so far, it seems the only way to satisfy those of us who are concerned that our books aren't looking the best they can be is to have a smaller minimum chunk size. Otherwise the temptation is great to add a comment with dummy text to pad it out--except Eric has said he might be planning to remove html comments (which I think is not a good idea because the submitter of the book would not have used comments unless they thought they were needed/helpful).
> 
Use  `<div class="section"> ` We could make another class name for pseudo-sections but I think that just adds complexity. Reducing chunk size will intorduce a raft or new problems, so that's not really an option.

**Comment by eshellman** [comment]
I think the disconnect here is expecting sections to cause hard breaks before the section rather than after. It seems to me that properly documenting the behavior will provide all the functionality you are asking for.

**Comment by eshellman** [comment]
also, div.chapter works the sam way as div.section

**Comment by eshellman** [comment]
Apologies for the misinformation chunks should be emitted BEFORE the sections, or div.sections.
It seems that the thing that's causing problems is the minimum chunk size. I'll see what I can do. Yes I know that's exactly what @jj2017 was saying.

**Comment by eshellman** [comment]
OK, I'm changing the MIN_CHUNK_SIZE to 256 bytes from 1024 bytes. MIN_CHUNK_SIZE was created to avoid the case where the chunker was emitting empty pages before sections.

Sorry for the confusion; it was quite hard for me to figure out what you intended the pages to look like.

**Comment by eshellman** [comment]
Note that the padding approach will only work  with `section`, `div.section` and `div.chapter`
So, if you REALLY want a hard, blank page in an epub, `<div class='section'>[230spaces]</div>` _directly under_ `<body>` will do the trick.

**Comment by charliehoward4dp** [comment]
> MIN_CHUNK_SIZE reduced from 1024 bytes to 256 bytes. [fixes](https://github.com/gutenbergtools/ebookmaker/commit/d42b79329e14b627112004eb1d0554f7049b7e3c) https://github.com/gutenbergtools/ebookmaker/issues/147

THANK YOU!!!

**Comment by jj2017** [comment]
Wow, thank you, thank you, thank you. Only a PGer/DPer could say this will be the best Christmas present yet!
