### ISSUE TITLE
Generated HTML5 inadequately protects h2 in header

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#150]
Reference two files on the landing page for etext 69058, the [as submitted](https://www.gutenberg.org/files/69058/69058-h/69058-h.htm) HTML and the [generated HTML5](https://www.gutenberg.org/cache/epub/69058/pg69058-images.html).
The generated HTML5 replaces the as-submitted tag with an `<h2>` but it inadequately protects the `<h2>` tag from the post-processor's CSS. An inline "style=" is used to partially protect from user's CSS but it is incomplete. It lacks assuring the default values (see [this page](https://www.w3schools.com/cssref/css_default_values.php) for h2's defaults). Even that would be inadequate for this etext, since the post-processor has styled the h2 with a `letter-spacing` attribute, which is not in the W3C list.
To close this issue, it seems that the h2 generated by the HTML5 conversion code must be hardened against user styling all h2's in CSS.

**Comment by eshellman** [comment]
The letter-spacing CSS attribute is allowed by PG. We could add every possible attribute to every styled element in the generated text, or we could ask the PP not to do that.

As it's likely that the generated text will be redesigned in Ebookmaker v0.13 (see discussion here: #139 ) We won't address this in v0.12.

**Comment by asylumcs** [comment]
Perhaps consider adding "all: initial" to tags used in the header and footer to assure that user's CSS does not get applied to header/footer elements.

**Comment by nfenwick** [comment]
Yes that's a surprise. I don't know what validator you are using to get it to fail. Its usage is described [here](https://www.w3.org/TR/css-cascade-3/#all-shorthand) in the CSS Cascading and Inheritance Level 3 documentation, which has REC status. It validates just fine with [this](https://validator.w3.org/nu/) validator, which is the only one I use for HTML5.

**Comment by nfenwick** [comment]
Whoops. Now that it's posted, I see I was logged in as Nell, not myself.  --Roger

**Comment by eshellman** [comment]
can confirm it validates with the current nu validator. (23.1.8) I was hoping this would be easy, but maybe I need to fix my nu validator and maybe update others.

**Comment by eshellman** [comment]
production has 20.6.30 I have 20.6.30 online ebookmaker has 23.1.11

**Comment by eshellman** [comment]
As part of the header refactor, `all: initial` has been added to a number of styles in the header stylesheet -  see ebookmaker.writers.HTMLTemplates  I found that it was too big a hammer to use on everything, so it's still possible for the user's stylesheet to modify the header styling, but the use of #pg-header in the selector should minimize inadvertent style leakage.
