### ISSUE TITLE
CSS all:initial reported as an error

### ISSUE THREAD

**Issue by nfenwick** [gutenbergtools/ebookmaker#152]
Using `all:initial` results in `CSS: “all”: Property “all” doesn't exist.` That CSS is used to protect PG eBook headers and footers from being styled by user-provided CSS. The Nu validator validates it without warning or error. It is a valid property as described explicitly in section 3.1 of the "CSS Cascading and Inheritance Level 3" recommendation. That spec has REC status. Reference https://www.w3.org/TR/css-cascade-3/.

**Comment by eshellman** [comment]
installed the current validator on production
