### ISSUE TITLE
generated HTML5 is dropping Credits

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#153]
Example eBook:

"as submitted" includes the credits:
https://www.gutenberg.org/files/65982/65982-h/65982-h.htm

generated HTML5 does not:
https://www.gutenberg.org/cache/epub/65982/pg65982-images.html

Same this happens for the next book, 65983, and others.

**Comment by eshellman** [comment]
At the time when that book was released, The credit heading should have been "Credit:". "Produced by:" became a valid heading for Gutenberg metadata in 2022. Most of the backfile put production credits _after_ the `*** START OF...` separator, and ebookmaker attempts to preserve such credits.

ebookmaker does no metadata updates after the initial release.
