### ISSUE TITLE
Incorrect parsing of subtitle

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#154]
It appears that ebm is using a colon in the title as an indicator of a subtitle. This is incorrect, and results in incorrect headers on the generated HTML.

We have subtitle captured in the clearance+submission data as a separate field. There is no separate subtitle field in the catalog database, but subtitles and titles are usually separated by a return <CR><LF> or whatever.

See for example: https://www.gutenberg.org/ebooks/69852 .. from the JSON:

 ```
 "TITLE": "Westminster Abbey: the last days of the monastery",
  "SUBTITLE": "as shown by the life and times of Abbot John Islip, 1464-1532",
```
'But the generated HTML incorrectly displays:
```
Title: Westminster Abbey
  the last days of the monastery
  
.. omitting the actual subtitle.

```
The catalog database also has it wrong:
```
gutenberg=> select title from books where pk='69852';
----------------------------------------------------------------------------------
 Westminster Abbey: as shown by the life and times of Abbot John Islip, 1464-1532

```
That seems to be a problem with fileinfo parsing the JSON, so perhaps is a separate issue. But regardless, for ebm to interpret the : as a subtitle separator is not correct.

You can see the same erroneous behaviour in https://www.gutenberg.org/ebooks/69857

The JSON:
 ```
 "TITLE": "Pride and Passion: Robert Burns, 1759-1796",
  "SUBTITLE": "",

```
The catalog has it correctly:
```
gutenberg=> select title from books where pk='69857';
------------------------------------------
Pride and Passion: Robert Burns, 1759-1796

```
But the generated text incorrectly does this:
```
Title: Pride and Passion
Subtitle: Robert Burns, 1759-1796

```
This seems to be simply an inappropriate use of a colon as a subtitle separator. Instead, JSON -> fileinfo -> the catalog database should be used.

**Comment by gbnewby** [comment]
Wow, github added inappropriate formatting for my issue report. Pretend what's above is all in monofont.

**Comment by eshellman** [comment]
As you are aware, the PG catalog does not store subtitles separately from titles. When a subtitle is supplied in the json, a colon is being used to include it in the title. Should we be instead discarding the subtitle? or using linefeeds as the delimiter? @asylumcs ? I will move this issue to libgutenberg, where the metadata handling occurs
