### ISSUE TITLE
Suggestion to remove limit in the page number string length limit of 10

### ISSUE THREAD

**Issue by Patoruzu45** [gutenbergtools/ebookmaker#155]
I was having a problem with the ebooks created from HTML versions built with Guiguts because there is a limit in the page number string length limit of 10. Is there any chance that that limit can be removed or increased?

The problem I detected was that the epub and mobi versions I created showed weird blanks in the middle of the text. I have checked and those happen when there is a page break. I am attaching the whole set so you can see. You can search for the string “pensando en su facienda”.

In the ebook versions, both epub and mobi, there is a significant blank space between “su” and “facienda”. And what creates the problem is the following page break coding:

_uno blanco é el otro negro, royendo siempre que non quedaban; et él pensando en su
<span class="pagenum" id="Page_xxxiii">[Pg xxxiii]</span>facienda é buscando arte_

[origenes1.zip](https://github.com/DistributedProofreaders/guiguts/files/10490435/origenes1.zip)

Thanks

Andrés

**Comment by windymilla** [comment]
[Looks like the code](https://github.com/gutenbergtools/ebookmaker/blob/master/src/ebookmaker/writers/EpubWriter.py#L803-L805) has been around for "ever". 

The problem occurs with Roman numerals, where `[Pg xxxiii]`, or longer, fails the test. I think the length test could be safely removed, since only elements that have certain classes are stripped. If you want to keep the test, then I guess changing 10 to 17 would cover everything up to a 1000 page book - the longest in Roman numerals is 888: `[Pg DCCCLXXXVIII]`

**Comment by eshellman** [comment]
I backwards compatible way to deal with this is to pick or create a class to be exempt from the limit. Currently, the remove list is: pagenum pageno page pb folionum foliono versenum verseno.

**Comment by windymilla** [comment]
I really think increasing the limit from 10 to 17 is unlikely to cause backwards compatibility issues. If you think what that would mean - someone has used the pagenum (or similar span) for something that is not a page/verse number, and it has between 11 and 17 characters, and it's something they wanted to be shown not hidden. Very hard to imagine what that might be.
If you feel really strongly about it, could you just increase it for `pagenum` then?

**Comment by eshellman** [comment]
will exempt pagenum and add logging to see if other classes are exceeding the limit.

**Comment by windymilla** [comment]
Thanks - sounds great!

**Comment by Patoruzu45** [comment]
Thanks Eric and Nigel!

 

Andrés

 

 

 

“No esperes nada del hombre que lucha por su vida y no por su eternidad”

 

Antoine de Saint Exupery

 

 

“La Humanidad achaca todas las calamidades a la acción de los malvados. Subestima a los estúpidos”

 

A.  Bioy Casares

 

 

«El que se inclina ante los poderosos muestra su trasero a los oprimidos»

 

Millor Fernandes:

 

 

“Todos los hombres dicen más o menos lo mismo. Sólo sus acciones permiten ver en qué difieren”

 

Molière

 

"Yo no creo en las sociedades maravillosas y perfectas que dan malos dirigentes. Hay un poco de reflejo."

 

El enmascarado solitario

**Comment by Patoruzu45** [comment]
Thanks Erik!
Regards.
Andrés

    On Thursday, February 16, 2023 at 07:13:35 p.m. GMT+1, Eric Hellman ***@***.***> wrote:  
 
 


Closed #155 as completed via #160.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
  

|  | Virus-free.www.avg.com |
