### ISSUE TITLE
repeated emails sent to Notify list

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#156]
All the email addresses in the Notify field of the JSON are getting notified, and this is happening every time a file is pushed--not just for the initial posting. So if there is an errata fix a year down the line, even then everyone on the original list will get a new email.

**Comment by asylumcs** [comment]
Note: this is for Workflow3 processing only.

**Comment by eshellman** [comment]
moved to https://github.com/gutenbergtools/ebookmaker/issues/156
