### ISSUE TITLE
posting notification wording

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#157]
When a eBook posts or attempts to post, an automated email is sent out. The information it includes is less than dp_post@pgdp.net should get. Not even the title of the book is in the email. It is also very impersonal.

The way this has been for years in that only the whitewasher sends out the posting notice when the WWer has determined that the file posted successfully. The message they send, including to dp-post when appropriate, includes a polite Thank You to the people who made the eBook as well as the title and ebook number.

**Comment by asylumcs** [comment]
Note: this is for Workflow3 processing only.

**Comment by eshellman** [comment]
Moved to https://github.com/gutenbergtools/ebookconverter/issues/29
