### ISSUE TITLE
backend notifications going to wrong people

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#158]
When a project attempts to post, if there is a problem then a backend notification is sent out. That notification should not go to everyone on the Notify list as it now does. It should go to the whitewasher (as it now does not). There is nothing the submitter, post-processor, etc. can do to remedy a backend notification. Only the WWer can do that, by correcting and resubmitting.

**Comment by asylumcs** [comment]
Note: this is for Workflow3 processing only.

**Comment by eshellman** [comment]
moved to https://github.com/gutenbergtools/ebookconverter/issues/29
