### ISSUE TITLE
HtmlTemplates.py includes byline, should not

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#161]
In HtmlTemplates.py, line 122, the title line includes the author name. It should only be the title per earlier conversations.

The Project Gutenberg eBook of Hidden blood
is preferred to the current "Read this book online" version:
The Project Gutenberg eBook of Hidden blood, by W. C. Tuttle

**Comment by eshellman** [comment]
I'm afraid I don't remember any discussion of that.

**Comment by eshellman** [comment]
fixed in 0.12.30
