### ISSUE TITLE
possible superfluous strong tags in header

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#164]
In the pg header, the `<strong>` tag surrounds the labels. For example:
```
        <p><strong>Release date</strong>: February 18, 2023 [EBook #70059]</p>
        <p><strong>Language</strong>: English</p>
```
and then strong is overridden in CSS to `font-weight: normal`. The rendering effect is as if `<strong>` is not there. Unless it is there to signal importance, unstyled, is it superfluous, perhaps an echo from the previous implementation, where it did render as bold?

**Comment by eshellman** [comment]
this is separating the semantics from the presentation, and was intentional.

**Comment by asylumcs** [comment]
ok thanks for explaining.
