### ISSUE TITLE
inadequately protecting PG header/footer CSS

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#165]
Though we now have a CSS block for the pg header and footer, it comes before the CSS block provided by the user and therefore is easily overwritten. In etext 70060 published today, the user has styled the `<h2>` to have a solid line above and below. They have styled the `<p>` tag to have `text:justify`. In both cases, the user's CSS affects the presentation of the PG header and footer adversely, as shown in the screenshot attached.
![70060-h2-override](https://user-images.githubusercontent.com/37535965/219900581-dd565867-8e86-4d65-a978-8987dd11124d.png)

**Comment by eshellman** [comment]
partial fix in 0.12.30
