### ISSUE TITLE
Quell notifications to production team

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#168]
I thought this was raised earlier but didn't see an open issue for it.

The production team (whitewashers) consensus is they do not desire to get "Good news, PG whitewasher(s)" emails when a new title is successfully processed on ibiblio.

They only want to get an email if there is an error (not just a warning) during processing.

Thanks.

**Comment by eshellman** [comment]
moved tp https://github.com/gutenbergtools/ebookconverter/issues/33
