### ISSUE TITLE
add article to down-conversion list 

### ISSUE THREAD

**Issue by rhynec** [gutenbergtools/ebookmaker#172]
While PG has embraced HTML5, it seems that the additional tags it defined are not recognized by ebookmaker. Manually defining the namespace "http://www.w3.org/1999/xhtml" inside the html file does not work either.

Does ebookmaker disallowed using tags like  \<article\> for a particular reason? Is it for backwards compatibility? If so, wouldn't it be better to throw a warning rather than an error in the output, and silently replace the tag as it does now.

**Comment by eshellman** [comment]
According to release notes (see [CHANGES](https://github.com/gutenbergtools/ebookmaker/blob/master/CHANGES)) article is indeed supported as a top-level element below body.

If you have encountered a problem, please include source files, a description of what you did, a description of what you expected, and a description of what you got. Thanks!

**Comment by rhynec** [comment]
I'm trying to nest multiple <article> elements (representing poems) inside a <section> elements (representing chapters). Section tags allow flow content, so I assumed <article> tags were valid children, but I keep getting the following error:

`CRITICAL:root:ERROR(RSC-005): /htdocs/ebookmaker/cache/20230321073733/10011-epub.epub/10011/7913627962069328267_book-0.html.html(48,10): Error while parsing file: element "article" not allowed anywhere; expected the element end-tag, text or element "a", "abbr", "acronym", "address", "applet", "b", "bdo", "big", "blockquote", "br", "cite", "code", "del", "dfn", "div", "dl", "em", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "iframe", "img", "ins", "kbd", "map", "noscript", "ns:svg", "object", "ol", "p", "pre", "q", "samp", "script", "small", "span", "strong", "sub", "sup", "table", "tt", "ul" or "var" (with xmlns:ns="http://www.w3.org/2000/svg")`
