### ISSUE TITLE
Online Ebookmaker: Unicode corruption in table of contents

### ISSUE THREAD

**Issue by remline** [gutenbergtools/ebookmaker#176]
1. Create an HTML file with the following contents:

```
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>t</title></head>
<body><h2>betaβ</h2></body>
</html>
```

2. Upload the HTML file to ebookmaker.pglaf.org.
3. Open the generated KF8 file.
4. Note that the table of contents contains **betaÎ²** rather than **betaβ**.

Notes:
- The corruption happens only in the KF8 file. Epub, Epub3, and "Kindle" are fine.
- I cannot reproduce this issue with my local ebookmaker installation.
- I suspect this may be a bug inside Calibre. Locally, I use Calibre 6.14.1, while pglaf.org evidently uses Calibre 6.4.0.
- I don't know if this impacts gutenberg.org production, which uses Calibre 4.17.0.

**Comment by eshellman** [comment]
how are you opening the KF8 file?

**Comment by remline** [comment]
I see a corrupt table of contents when opened on either Kindle Paperwhite 11th Generation or Calibre's ebook-viewer (6.14.1).

**Comment by eshellman** [comment]
thanks.

**Comment by eshellman** [comment]
works correctly in Calibre6.8(mac). Has to be a Calibre bug
