### ISSUE TITLE
h2 in PG header/footer has undesirable effects on TOC

### ISSUE THREAD

**Issue by rhynec** [gutenbergtools/ebookmaker#177]
Currently DP recommends using the \<h1\> tag only for the title in the titlepage, and using \<h2\> for any sections of the book. However, the PG header and footer both use \<h2\> tags for formatting titles, which forces them to appear in the final generated TOC. This will result in most books having their \<h1\> tag come after the header's \<h2\> tag, and will make every ebook appear to have two titles in their TOC (The Project Gutenberg eBook of... plus the title designated by the proofreader). In addition, since the \<h2\> tag of the license comes after the copyright notice of the footer, this notice will appear to either belong to the previous chapter, or leave it "floating" without a proper entry in the TOC. Ignoring these headers for TOC generation, or giving them special treatment (e.g. manually add TOC entries title "License" and "Info") would be better.

In general, I also think the way TOCs are generated should be tweaked moving forward. There should be additional methods to add entries to the TOC without explicitly adding a header in your html/ebook. For example, defining an \<hr\> class which manually inserts a TOC entry when found, or having each section with a title be added without needing an \<h#\> within.

Edit: Sorry if anyone got a horribly formatted email notification about this issue. I forgot that \< and \> are special characters in Github.

**Comment by eshellman** [comment]
IIRC the h2 markup was a consequence of the HTML5 validation of the section element used for the heading.

But these are good points.
