### ISSUE TITLE
Treatment of multiple authors

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/ebookmaker#181]
(relocating discussion from #139)
@gbnewby:
I'd like to see better presentation of multiple creators (authors etc.) in the head section.

Currently, labels are repeated. For example:

The non-generated file in https://www.gutenberg.org/files/69679/69679-h/69679-h.htm has:

Authors: Charles Francis Adams
Gilbert Nash
Charles Francis Adams III

The generated file in https://www.gutenberg.org/cache/epub/69679/pg69679-images.html has:
Author: Charles Francis Adams
Author: Charles Francis Adams III
Author: Gilbert Nash

The first way is much more visually appealing. Even better would be:
Authors: Charles Francis Adams, Gilbert Nash and Charles Francis Adams III

@eshellman:
With regard to the repeated authors, what we actually have in the database is a list of creators, which includes illustrators, translators, editors, etc. Since the order of authors is usually presumed to be significant, we shouldn't want to change that in the generated list. but it seems the order may not be preserved in the db - will need to look at that.

Provided we can reconstitute the author order, it's probably easy to do "author1, author2, illustrator1 (ill), illustrator2(ill), translator1 (trl)".

Except.... the Creator names in our database are stored in the form "Lastname, Firstname, Suffix, (Parenthetical)" So there will inevitably be some reconstituted authorlists which are either mangled or ugly. The advantage of putting each creator on a separate line is that it will accurately reflect the contents of the database, which can be updated as need be.

@eshellman:
sample authors:
"Quintus, Smyrnaeus, active 4th century"
"Du Bois, W. E. B. (William Edward Burghardt)"
"Library of Congress. Copyright Office"
"John of Damascus, Saint"
"John Murray (Firm)"
"Caine, Hall, Sir"
"Plato (spurious and doubtful works)"

@gbnewby:
My suggestion was not to fix the weirdness in how authors are presented.
The idea is just to not repeat the Author: tag.

Separating by semicolon could work, for example:

Authors: Du Bois, W. E. B. (William Edward Burghardt); John Murray (Firm);
Library of Congress. Copyright Office
[…](https://github.com/gutenbergtools/ebookmaker/issues/139#)

@gbnewby:
On the creator list (the few comments above this one): I looked in the code, and it seems we are only using the dc.authors field. I.e., generated HTML only includes the Authors, not the Illustrators, Editors or Translators.

I would like those other types of creators to be presented when they exist (there are some other creator types that could be of interest but seem less important.. it might be just as easy to list all creator types when they exist).

Simulated example building on the prior comments above:

Authors: John Murray (Firm); Du Bois, W. E. B. (William Edward Burghardt)
Illustrator: Caine, Hall, Sir
Editors: Plato; Socrates

... you get the idea? When there is more than one, use "Authors" instead of "Author."
When there are multiple, separate with a semicolon.
Only list Author/Illustrator/Editor/Translator when those field exist.

Thanks for considering. I was going to make a PR myself but the data structure for the creators (like dc.authors), and the pstyle() function for formatting, made it more challenging than just updating the iteration loops.

@eshellman:
dc.authors is a list of author objects, each of which has a name, a creator role, a birthdate and a deathdate. So editors, translators etc are in fact listed. The list is ordered so separating out the creators by roles may re-order the list of creators. We use the MARC list for roles. The importance of a role may depend on the type of work.

@gbnewby:
Ok, then it sounds like this will require first aggregating each type of role then emitting them in groups like my example.

@eshellman:
It looks like this is already done - look at https://gutenberg.org/ebooks/830

@gbnewby:
Indeed, the multiple roles seem to be listed. But they are not consolidated as in my example above.

See for example: https://gutenberg.org/cache/epub/27991/pg27991-images.html

The creator listing in the HTML5:
Author: Georgette Leblanc
Author: Maurice Maeterlinck
Editor: Frederick Orville Perkins
Translator: Alexander Teixeira de Mattos

But should be:
Authors: Georgette Leblanc; Maurice Maeterlinck
Editor: Frederick Orville Perkins
Translator: Alexander Teixeira de Mattos

@eshellman:
How important is consolidation? Consolidation adds considerable complexity to the code and makes it harder for downstream users to parse, or to translate, when that is desired. Currently we only need the singular form of the role name in english. Adding 's' fails for 2 of the roles in our db. We do not consolidate roles in the bibrec page, which would not be able to use the same consolidation code. Issues related to line wrapping are exacerbated.

@gbnewby:
I think consistency is extremely important, and that already has been part
of our discussion. The format I suggested is what's been used for a very
long time. The main variation is the representation of names in the
database isn't always great for presenting as-is, but this issue exists
regardless of consolidation.

My suggested format should be straightforward algorithmically. We can
discuss as desired to ensure challenges can be addressed.

The bibrec section is a table, and the creators are presented as a
hyperlink in that table. I don't mind consolidating those records, but
don't see it as needed for consistency. Since it's tabular data, a single
key-value pair makes sense to me - i.e., status quo.

The book itself is targeted at human readers, and it seems obvious to me
that consolidation is a friendlier way of presenting the creator roles.

Anyone trying to scrape the books for metadata is going down a pathway that
we don't support. But even if they did, I don't see how the recommended
format is less amenable to automation than the current non-consolidated
format.
  ~ Greg

@eshellman:
In particular, our own author parsing code (used by e.g. online ebookmaker). doesn't handle the suggested consolidated format correctly and would need to be revised. The format that ebookmaker expects (not my code) is comma delimited, not semicolon delimited. Yes, we need to be able to scrape our own files.

It's ironic that you use 27991 as an example, because the book has only one author, Georgette Leblanc (a.k.a. Madame Maurice Maeterlinck) https://en.wikipedia.org/wiki/Georgette_Leblanc

**Comment by eshellman** [comment]
Looking at the backfile, the vast majority of submitted files deal with multiple authors like this:
```
Author: Oliver Wendell Holmes
        Dinah Maria Mulock Craik
        Harriet Prescott Spofford
        John Wilson
        Allan Cunningham

Editor: Rossiter Johnson


```

https://gutenberg.org/files/61422/61422-h/61422-h.htm

Given the expressed desire for consistency, I will present each author on a separate line in the generated header, omitting any repeated header. This will be a simple change and is compatible with the existing parser.

**Comment by gbnewby** [comment]
I like this proposed solution a lot, especially since it seems relatively
easy to implement:

Author: Oliver Wendell Holmes
        Dinah Maria Mulock Craik
        Harriet Prescott Spofford
        John Wilson
        Allan Cunningham

Editor: Rossiter Johnson

Once it's implemented, we'll also want to update the Workflow tool for
original postings, to match.

Further question: From the examples, it's not clear whether these
creators are drawn directly from the database, or if there is any
reformatting. Point to the code, if there is reformatting, so Workflow
can follow.

Please choose an order for creator types, and determine whether we
should always include all creator types. The ones that seem most
important:

Author

Illustrator

Editor

Translator

**Comment by eshellman** [comment]
The examples from my last comment are from the submitted file.

Let discuss the creator roles on #180
