### ISSUE TITLE
Clear out GTM chaff as used by PG Australia; add tips to documentation

### ISSUE THREAD

**Issue by dwids** [gutenbergtools/ebookmaker#182]
Thanks for the software suite, it's excellent. 

I see that some older HTML books on PG **Australia** (PGA), like [His Prey Was Man](https://gutenberg.net.au/ebooks12/1203781h.html), have some items which seem to cause issues with _ebookmaker_.  It didn't take long to find a quick work around via **manually** editing the html file:

1.  Remove everything between 

```
<!-- Google tag (gtag.js) -->
...and
<!-- End Google Tag Manager -->
```
**including** the two `<!--...>` lines 

2. Save and then process the updated file in  _ebookmaker_. It should then work.

### Other Notes
- I use the _Download Them All_ browser add-on to grab the images from the PGA page
- Under Windows 10, WSL (Ubuntu 22.xx) works very well with ebookmaker.  I found the installation steps worked very well, with one or two minor changes...happy to document these if you want.
- From native Windows you can directly access (and copy/delete) Ubuntu files. From Windows Explorer, I go to  `\\wsl.localhost\Ubuntu-22.04\home\user` where _user_ is your Windows 10 user name, like _david_  . It's easy to copy the images from Windows to Ubuntu - for ebookmaker to use - then copy the new epubs back.

**Comment by eshellman** [comment]
shoudn't be hard to remove whatever was causing the problem

**Comment by dwids** [comment]
Thank you
