### ISSUE TITLE
modify boilerplate warning

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/ebookmaker#184]
"WARNING" messages about boilerplate are not relevant except to whitewashers and errata workers.

One possibulity is to change these to "INFO" massages but to change the log message to something like:
`INFO: No Boilerplate. This is an ERROR for submitted source files.`

**Comment by windymilla** [comment]
Sounds like it could be helpful to reduce the severity from WARNING to INFO.
However, I think that log message wording could be misinterpreted by people using the online ebookmaker to check their file before submitting. They may think if it is an "ERROR for submitted source files" that they need to fix something before they are permitted to submit it for upload. I'm not sure what the wording should be, maybe "ERROR for whitewashed source files"?
