### ISSUE TITLE
Automatic transformation in epub (damn => dang)

### ISSUE THREAD

**Issue by Khardan64** [gutenbergtools/ebookmaker#185]
1. Create a file with the following content: 

```
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Mon titre</title></head>
<body><h2>condamné damné condamnation calomnie - damn demn dimn domn dumn - amn emn imn omn umn - mn</h2>
</body></html>
```
2. Upload the HTML file to ebookmaker.pglaf.org.
3. Open the epub file generated
4. Note that the text in the epub now contains: 
**condangé** **dangé** **condangation** calomnie - **dang** demn dimn domn dumn - amn emn imn omn umn - mn

Note: 

- It seems to be done with this group of letters: **damn**
- I detected it when I started reading the epub of this book: _L'affaire Lerouge_ from _Émile Gaboriau_ (#15579 -  https://www.gutenberg.org/ebooks/15579)   with its epub generated with this tag(`<meta name="generator" content="Ebookmaker 0.12.30 by Project Gutenberg"/>`) 
- I found the same problem in two other books containing this false word _condangé_ or a declinaison of it instead of _condamné_: for example inside _Le comte de Monte-Cristo_, Tome I by _Alexandre Dumas_ (#17989 - https://www.gutenberg.org/ebooks/17989)
- It may impact all the (french) epub in the gutenberg library; although the cover image is not impacted (see this book: _Le Dernier Jour d'un Condamné_ by _Victor Hugo_ - #6838 - https://www.gutenberg.org/ebooks/6838. The cover is good but the text on the first page is `The Project Gutenberg eBook of Le Dernier Jour d'un Condangé` and the text is full of "_condangé_" words)
-

**Comment by Khardan64** [comment]
In the same way, the word _damnation_ is changed into _condemnation_.

1. Create a file with the following content: 

```
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>My title</title></head>
<body><h2>The Damnation of Theron Ware</h2>
</body></html>
```
2. Upload the HTML file to ebookmaker.pglaf.org.
3. Open the epub file generated
4. Note that the text in the epub now is: 
The **Condemnation** of Theron Ware

Note:
* _The damnation of Theron Ware_ is a book already in the gutenberg library here (# 133 -  https://www.gutenberg.org/ebooks/133). The epub generated contains:

> The Project Gutenberg eBook of The Condemnation of Theron Ware
> Title: The Condemnation of Theron Ware
> *** START OF THE PROJECT GUTENBERG EBOOK THE CONDEMNATION OF THERON WARE ***
> ...
> *** END OF THE PROJECT GUTENBERG EBOOK THE CONDEMNATION OF THERON WARE ***

**Comment by windymilla** [comment]
I just tried exactly that, and didn't get any transformation of `damn` into `dang`
See this cache: https://ebookmaker.pglaf.org/cache/20230430114741/

What epub reader are you using? Maybe that is what is causing the issue?

**Comment by windymilla** [comment]
Similarly, book #133 has "The damnation of Theron Ware" not "condemnation"
I checked ADE ebook reader and Calibre ebook viewer

**Comment by srjfoo** [comment]
Agreeing with @windymilla -- I didn't do multiple books, but I did try [#133](https://github.com/gutenbergtools/ebookmaker/pull/133), and viewed in Apple's Books app on both computer and iPad, and saw no substitution.

**Comment by Khardan64** [comment]
I found the problem and it comes from my own.
There was an extension installed in my calibre (Language cleaner) and it affects the reader: changing all offensive language words to others. 
(The problem now, but only for me is that this extension modifed directly all the epub opened with the ebook reader and changed the words inside of them). 

I'm really sorry for the time you may have spent on this :-<

**Comment by Khardan64** [comment]
I found the problem and it comes from my own.
There was an extension installed in my calibre (Language cleaner) and it affects the reader: changing all offensive language words to others. 
(The problem now, but only for me is that this extension modifed directly all the epub opened with the ebook reader and changed the words inside of them). 

I'm really sorry for the time you may have spent on this :-<

**Comment by windymilla** [comment]
Thanks for the update @Khardan64 - glad you solved the mystery.
