### ISSUE TITLE
boilerplate not added to generated txt files when there is no html source.

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/ebookmaker#186]
may already be fixed - add a test.

**Comment by asylumcs** [comment]
test files added as requested:
  easymoney-naked.txt
  easymoney-naked-with-sentinels.txt
  
[easymoney-naked.txt](https://github.com/gutenbergtools/ebookmaker/files/11915792/easymoney-naked.txt)
[easymoney-naked-with-sentinels.txt](https://github.com/gutenbergtools/ebookmaker/files/11915794/easymoney-naked-with-sentinels.txt)

**Comment by eshellman** [comment]
After starting on this, I realized the desired behavior is not well specified.

My understanding: 
1. For ebookmaker alone (as on online ebookmaker) we're not concerned about boilerplate addition.
2. for "dopush" and rebuilds, we want there to be boilerplate generated from db  (or from json or header on the first push) added for all generated files (txt included.) Here the metadata is supplied to ebookmaker by ebookconverter.

Is that a fair summary?

**Comment by gbnewby** [comment]
1. I'm not sure I understand. It already does boilerplate addition (see https://ebookmaker.pglaf.org). So, I'd say we're not looking for any change in behavior.
2. Yes, exactly. That is also status quo, I believe. Every new eBook push is accompanied by a JSON already. Any update/errata push already has catalog info. 

For #2, I'm not sure that you ever need to consult the header (though perhaps ebookconverter already does this, in which case I'm not looking for a change in behavior).

**Comment by eshellman** [comment]
1. it's not adding boilerplate to txt. if you give it htm, is will add boilerplate to htm and the emit a txt version
2. ebookconverter won't add boilerplate to txt if the source is txt. fixing that for this issue

**Comment by gbnewby** [comment]
It's important for ebookmaker to emit txt with boilerplate if text is the only input. That is the specific gap we are trying to get addressed.
