### ISSUE TITLE
Input HTML needs to be validated, not just generated HTML

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#192]
PG has had several recent uploads via https://upload.pglaf.org where the HTML had validity errors. The errors in the uploaded text were not reported in the output.txt of https://ebookmaker.pglaf.org

Upon investigation & discussion, it appears this is because ebm runs the validator (vnu.jar) against the generated HTML5, but not against the uploaded HTML. 

Since the uploaded HTML is posted to the 1/2/3 filesystem, it needs to be validated.

Is this something to add to ebm? Otherwise, we could add a call to the validator before calling ebm in https://ebookmaker.pglaf.org

Here is a simple example with a one-line HTML file that has a validation error. Online ebm reports no errors (see https://ebookmaker.pglaf.org/cache/20230715224619/output.txt [will be automatically purged after 3 days]). 

Running validator.w3.org directly spots the error, of course: ![Screenshot 2023-07-15 at 11 49 28 PM](https://github.com/gutenbergtools/ebookmaker/assets/23138734/c097e4c3-afd3-4578-94b0-619e33d300c7)

Here's the simple file: [test0715.zip](https://github.com/gutenbergtools/ebookmaker/files/12065109/test0715.zip)

**Comment by eshellman** [comment]
Other than running time, I don't see any downside to running the validator or the input file before running ebm. In this case the error gets fixed by BeautifulSoup before Ebookmaker starts working on it, and warnings are not available.

**Comment by windymilla** [comment]
Would that mean that the validation errors would get reported to the user when they upload and/or in output.txt file? Since we now insist that the output.txt file doesn't have errors, that would be a good way of ensuring that files with validation errors don't get uploaded.

**Comment by jj2017** [comment]
In my naivety I thought ebookmaker was running directly on the submitted file and that the current upload form was saying it was okay to submit the file because no problems in the submitted file were reported. If we can't have it running on the submitted file, the upload process needs again to flag validator errors, which, I think would, at this stage, be a step backwards.
