### ISSUE TITLE
backend notification apparent false positive

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#207]
A recent backend notification recently came through for 22261. It included: "...sideborder.gif" does not appear to match the media type image/gif, as specified in the OPF file. All three gifs are reported as not being GIFs but they are:

capO.gif:       GIF image data, version 89a, 72 x 69
capT.gif:       GIF image data, version 89a, 62 x 74
sideborder.gif: GIF image data, version 89a, 15 x 157

It looks like EBM is not correctly detecting those as GIF images and then sending a false positive backend notification to the user.

**Comment by eshellman** [comment]
That message would be coming from the EPUB validator. How did you validate the three gifs?

**Comment by eshellman** [comment]
The image file in the epub is indeed a png file; I'm preparing a dot release for ebookmaker, I'll take a look to see what's going on - evidently ebookmaker's imgae code is writing a png and forgetting to change the file name.
