### ISSUE TITLE
multiline START OF line mishandled

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#209]
In an uploaded text file, a multi-line "START OF" line looks like this:

    *** START OF THE PROJECT GUTENBERG EBOOK DANGER SIGNALS
    REMARKABLE, EXCITING AND UNIQUE EXAMPLES OF THE BRAVERY, DARING AND
    STOICISM IN THE MIDST OF DANGER OF TRAIN DISPATCHERS AND RAILROAD
    ENGINEERS ***

In the generated text file, that gets an unexpected set of asterisks on the first line and it drops a line:

    *** START OF THE PROJECT GUTENBERG EBOOK DANGER SIGNALS ***
    STOICISM IN THE MIDST OF DANGER OF TRAIN DISPATCHERS AND RAILROAD
    ENGINEERS ***

This can be seen in these files:
uploaded: https://www.gutenberg.org/files/19007/19007-0.txt
generated: https://www.gutenberg.org/cache/epub/19007/pg19007.txt

**Comment by eshellman** [comment]
sorry, can't fix this. use a single line or truncate title at 80 characters

**Comment by eshellman** [comment]
need to check something

**Comment by eshellman** [comment]
Thanks @asylumcs that was a real bug

**Comment by asylumcs** [comment]
Glad to help.
