### ISSUE TITLE
Fails to install due to broken `cchardet` dependency

### ISSUE THREAD

**Issue by Lynnesbian** [gutenbergtools/ebookmaker#211]
The `cchardet` dependency has not been updated in some time, and [multiple people have reported issues](https://github.com/PyYoshi/cChardet/issues/81) building it with Python 3.11. Project activity has [completely stalled](https://github.com/PyYoshi/cChardet/commits/master/), making a patch unlikely.

A maintained fork is available [here](https://github.com/faust-streaming/cChardet), and should be a drop-in replacement.

**Comment by eshellman** [comment]
Thanks, this is good to know!
We're currently running on Py3.9, and I'm running on Apple M1 silicon, which the fork says is not supported. If you want to run with Py3.9, perhaps you can suggest an appropriate conditional install spec for setup.py ?
