### ISSUE TITLE
inconsistent generation of HTML

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#230]
When the source is text-only, a "Read online (web)" is not consistently generated.
https://www.gutenberg.org/ebooks/73804 does not have a landing page link to the generated HTML, https://www.gutenberg.org/cache/epub/73804/pg73804-images.html, even though that file exists.
https://www.gutenberg.org/ebooks/73809 is also a text-only upload which does display the "Read online (web)" link.

**Comment by eshellman** [comment]
Ebookmaker consistently generatesHTML even when txt is the only source.

Are you perhaps complaining the read online link is displayed second; this is odd. It could be caused by an incorrect sort value for a filetype in the database. I have created an issue in the autocat3 repo
