### ISSUE TITLE
text only uploads mishandle title punctuation

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#231]
https://www.gutenberg.org/ebooks/73810 was a text-only at upload. The title for this book is "Puhettako parantelemaan?" (translated: "Talk to Improve?"). The title is shown correctly on the landing page and within the text, but the ebookmaker-generated header has dropped the question mark from the title. See: https://www.gutenberg.org/cache/epub/73810/pg73810.txt.

**Comment by eshellman** [comment]
title was entered into the database without the '?' and later corrected:
`{
    "GENERATED": "2024/06/11 11:28:56",
    "VERSION": "3.04",
    "DATA": {
        "TITLE": "Puhettako parantelemaan",
        "SUBTITLE": "Yksin\u00e4yt\u00f6ksinen n\u00e4ytt\u00e4m\u00f6kohtaus",
        "CONTRIBUTOR": [
            {
                "name": "Santeri R\u00e4s\u00e4nen",
                "role": "author"
            }
        ],
        "SCANS_ARCHIVE_URL": [],
        "CREDIT": "Tapio Riikonen",
        "LANGUAGE": "Finnish",
        "PUBLISHER": "Arvi A. Karisto Oy",
        "PUBLISHER_PLACE": "H\u00e4meenlinna",
        "PUBLISHER_COUNTRY": "FI",
        "SOURCE_PUBLICATION_YEARS": [
            "pubdate:1924"
        ],
        "WW": "ajhaines@shaw.ca",
        "REQUEST_KEY": "20240512032557rsnen",
        "EBOOK_NUMBER": "73810",
        "NOTIFY": "Tapio Riikonen <tapri32@gmail.com>,  "
    }
}`
