### ISSUE TITLE
Image alt= tags with only spaces

### ISSUE THREAD

**Issue by rtonsing** [gutenbergtools/ebookmaker#239]
I have seen several ebooks that have `alt=" "` (with a space) for images, I assume to avoid the warnings from ebookmaker.
I don't know how text to speech readers handle this, but I would assume tags with only spaces should be treated the same as empty ones, they don't provide any useful information.

**Comment by eshellman** [comment]
You're probably correct. It's embarassingly common to put in things like `[image]` or `figure 3` which are much much worse.
