### ISSUE TITLE
Where is test suite, and how to run?

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#24]
In ebookmaker/README.md it says to run tests with `python3 setup.py test`, but where is this run from? It doesn't seem to be part of the installed pip virtual environment.

I tried this:
git clone https://github.com/gutenbergtools/ebookmaker
cd ebookmaker
python3 setup.py test

 .. but got errors. I had not built ebookmaker after git clone (since I followed the README instructions and installed with pip3, not git clone). 

Also, if Travis-CI has installable dependencies, those should be listed.

Thanks.

**Comment by eshellman** [comment]
after `cd ebookmaker` , first `git checkout dev`, then run `pipenv install -e .` This sets up a development environment. Then run `python setup.py test`.

You don't need to clone the repo to run ebookmaker, however.

**Comment by gbnewby** [comment]
Thanks for those steps. It appears my dependencies are ok.

I updated README.md to clarify the steps. In particular, "python3 setup.py
test" does not run correctly unless you first "pipenv shell" within the
environment you set up.
 - Greg

**Comment by eshellman** [comment]
or `pipenv run python setup.py test`
