### ISSUE TITLE
value "gla" not accepted for lang attribute - should be "gd"

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#243]
ebookmaker reports:

error: Bad value “gla” for attribute “lang” on element “span”: The language subtag “gla” is not a valid ISO language part of a language tag.

The code "gla" is the ISO 639-2 and ISO 639-3 language code for Scottish Gaelic according to
https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by eshellman** [comment]
on production or online?

**Comment by eshellman** [comment]
I'll take a look next week, but I'll need the book number.

**Comment by asylumcs** [comment]
41227 uses <span lang="gla"> for one example. I can provide others if needed.

**Comment by eshellman** [comment]
This is an error introduced in the november changes. "gla" worked fine in September.

Please check that you have not introduced an encoding error.

**Comment by asylumcs** [comment]
I am confused by the report in https://www.gutenberg.org/cache/epub/41227/pg41227.converter.log. The HTML seems to think "gla" should be okay based on this example line from the book:

M'Leods of Gairloch, who had the <i data-invalid-lang="fre">soubriquet</i> of <span lang="gla">Nimhneach</span>, or

The report issues a warning about "fre":

2024-11-26 09:07:02,769 WARNING   #41227 invalid lang attribute fre

but it seems to me the HTML has already indicated that. However the report for "gla" makes no sense:

"file:/export/sunsite/users/gutenbackend/cache/epub/41227/pg41227-images.html":24715.47-24715.63: error: Bad value â€œlatâ€ for attribute â€œlangâ€ on element â€œspanâ€: The language subtag â€œlatâ€ is not a valid ISO language part of a language tag.

That does look like an encoding error of the double quotes in the report, but not in the HTML. I checked the heading:

<meta charset="utf-8">

and I checked the encoding of the file:

$ file /data/ftp/mirrors/gutenberg/4/1/2/2/41227/41227-h/41227-h.htm
HTML document, Unicode text, UTF-8 text, with CRLF line terminators

The HTML for 41227 is properly encoded.

To test this further, I took one of my own books that passes ebookmaker with no errors and changed one line: 

<p>Intently the <span lang="gla">Leac nan Saighead</span> listened to that voice.</p>

Running this through ebookmaker, I get this output:

--- Starting ebookmaker processing
EbookMaker 0.12.47
CRITICAL:root:validation error reported by HTML_VALIDATOR:
CRITICAL:root:"file:/htdocs/ebookmaker/cache/20241128073930/out/10001-h.html":189.17-189.33: error: Bad value “gla” for attribute “lang” on element “span”: The language subtag “gla” is not a valid ISO language part of a language tag.

CRITICAL:root:validation error reported by HTML_VALIDATOR:
CRITICAL:root:"file:/htdocs/ebookmaker/cache/20241128073930/out/10001-noimages-h.html":189.17-189.33: error: Bad value “gla” for attribute “lang” on element “span”: The language subtag “gla” is not a valid ISO language part of a language tag.

--- ebookmaker complete

This does not seem to be related to encoding.

**Comment by eshellman** [comment]
Thanks for checking. it's looking like a validator issue with 3 letter language codes.
