### ISSUE TITLE
semi false positive for <ruby> tag

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#244]
<ruby> is an annotation tag used for CJK pronunciation assistance. 

We found these books using the tag:

31757, 32941, 32978, 33307, 34013, 34084, 34636, 34158, 35018, 35327, 36358, 36459, 36976, 37605, 37626, 38697, 39287, 41325, 43123, 62133

EBM currently rejects <ruby> with  Error while parsing file: element "ruby" not allowed anywhere.

In fact it's permitted in EPUB 3.0, and it's part of HTML5. I don't think it can be included in EPUB < 3, and don't know about the Kindle formats.

**Comment by eshellman** [comment]
I think this can be addressed in 0.12.48
