### ISSUE TITLE
Python errors when uploading files to ebookmaker

### ISSUE THREAD

**Issue by 70ray** [gutenbergtools/ebookmaker#4]
When uploading a test book page I get errors like "Nonetype object is not iterable".
I've looked into this and made some commits to ebookmaker and libgutenberg which enable it to get past the errors. But there could be another reason why the code gets to this place in this situation.

The last commits fix the problem. The earlier ones enable the code to run with python 2.7.
I tried with python 3 but some different problems occured with the imports in EbookMaker.py.
The file which caused the problems is attached.
[out.zip](https://github.com/gutenbergtools/ebookmaker/files/2744628/out.zip)

**Comment by eshellman** [comment]
If you could create a PR for the renovations branch, that would be great! I'll create a dev branch for libgutenberg as well.

**Comment by eshellman** [comment]
I've copied the renovations branch to a "dev" branch to make the roles clearer. Use it to propose code changes.

**Comment by 70ray** [comment]
I'll try rebasing onto the renovations branches. Should I be using Python 2.7?

**Comment by eshellman** [comment]
I'm working in Python 3.6.  But now I have all the relevant Python code, which I didn't have before, and I can see some work is needed - maybe you've seen the same things. Just in case we're doing the same thing - I'll make PRs based from the dev branches and leave them open for comment a while before merging.

**Comment by 70ray** [comment]
I tried it out in MSWindows 10 but ran into difficulties with paths and urls. Going back to linux for the time being.

**Comment by eshellman** [comment]
With a years more experience, I can say that that the error messages reported are most like a result of not using python 3.6+
