### ISSUE TITLE
div with no content is converted to self closing div which is not valid in html.

### ISSUE THREAD

**Issue by 70ray** [gutenbergtools/ebookmaker#53]
`<div class="whatever"></div>` is converted to `<div class="whatever"/>`.
Such an empty div might be intended for drawing a line without the semantic content of `<hr>`

**Comment by eshellman** [comment]
Those mean exactly the same thing in xhtml, and epub is using xhtml. Is this causing a problem? If so, information about your environment and use case would be helpful.

**Comment by 70ray** [comment]
It was the "-noimages-h.html" file produced by ebookmaker which does not display correctly in a browser.
I was experimenting with using a `div` with no content but a border to draw a horizontal line instead of an `<hr>`.
I've reverted to using `<hr>` so perhaps no need to do anything about this but I thought I'd mention it anyway.

**Comment by eshellman** [comment]
Oh, that makes sense. But why do you say they are displayed incorrectly? Perhaps you are trying to use css which ebookmaker doesn't like?

**Comment by 70ray** [comment]
Viewing the source from the browser for `<div class="line w10"/>` it says "Self-closing syntax used on a non-void HTML element. Ignoring the slash and treating as a start tag" so everything subsequent takes the properties of "line w10" which in this case meant it only filled 10% of the width.

**Comment by eshellman** [comment]
Is the doctype

<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.1//EN' 'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd'>


What browser software is being used?

**Comment by 70ray** [comment]
Yes that is right.
I using firefox 77.0.1 (64-bit).
I can send you the files if you like.

**Comment by eshellman** [comment]
OK, I've verified the issue. Had no idea XHTML was not supported in modern browsers.

**Comment by eshellman** [comment]
EbookMaker is under the impression that the 'HTML" output is only used for rst input. Do you know any other circumstance where the xhtml files are used?

**Comment by 70ray** [comment]
Sorry, no I don't.
