### ISSUE TITLE
allow bgcolor?

### ISSUE THREAD

**Issue by eshellman** [gutenbergtools/ebookmaker#56]
On Jun 29, 2020, at 6:43 AM, Chuck Greif <cbgrf@yahoo.com> wrote:

Eric:

I have this question:

Some htm files have a body background color specified.
I know that Calibre manages to reproduce the colored backgrounds faithfully in epubs, etc.
I believe that most of the newer ereaders are in color, as opposed to years ago when we had only gray on gray.

This color enhances the text as intended by the producer.
I am wondering if we can not, may not, carry the specified background colors through to the epub/movi versions.

Two examples of colored backgrounds in the collection:

http://www.gutenberg.org/files/245/245-h/245-h.htm

http://www.gutenberg.org/files/62340/62340-h/62340-h.htm

Cheers,
Chuck

**Comment by eshellman** [comment]
From https://www.w3.org/TR/WCAG20/

1.4.3 Contrast (Minimum): The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)

Large Text: Large-scale text and images of large-scale text have a contrast ratio of at least 3:1;

Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.

Logotypes: Text that is part of a logo or brand name has no minimum contrast requirement.

1.4.6 Contrast (Enhanced): The visual presentation of text and images of text has a contrast ratio of at least 7:1, except for the following: (Level AAA)

Large Text: Large-scale text and images of large-scale text have a contrast ratio of at least 4.5:1;

Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.

Logotypes: Text that is part of a logo or brand name has no minimum contrast requirement.

contrast ratio
(L1 + 0.05) / (L2 + 0.05), where

L1 is the relative luminance of the lighter of the colors, and

L2 is the relative luminance of the darker of the colors.

Note 1: Contrast ratios can range from 1 to 21 (commonly written 1:1 to 21:1).

Note 2: Because authors do not have control over user settings as to how text is rendered (for example font smoothing or anti-aliasing), the contrast ratio for text can be evaluated with anti-aliasing turned off.

Note 3: For the purpose of Success Criteria 1.4.3 and 1.4.6, contrast is measured with respect to the specified background over which the text is rendered in normal usage. If no background color is specified, then white is assumed.

Note 4: Background color is the specified color of content over which the text is to be rendered in normal usage. It is a failure if no background color is specified when the text color is specified, because the user's default background color is unknown and cannot be evaluated for sufficient contrast. For the same reason, it is a failure if no text color is specified when a background color is specified.

Note 5: When there is a border around the letter, the border can add contrast and would be used in calculating the contrast between the letter and its background. A narrow border around the letter would be used as the letter. A wide border around the letter that fills in the inner details of the letters acts as a halo and would be considered background.

Note 6: WCAG conformance should be evaluated for color pairs specified in the content that an author would expect to appear adjacent in typical presentation. Authors need not consider unusual presentations, such as color changes made by the user agent, except where caused by authors' code.

**Comment by srjfoo** [comment]
Apologies for sticking my nose in if this is not the best place to offer an opinion, but this sounds like a case of the producer enforcing their idea of what an ebook should look like, regardless of what the user's settings are.

As a consumer of ebooks, I do not want the ebooks I read to have a background color enforced by the code unless the e-readers have the ability, readily available to the consumer, of overriding the colors. (In fact, I don't really appreciate it in the HTML, either -- that's the producer's opinion of what looks nice, and not mine, but at least for HTML, I can more easily change it, if I care enough, than I can for epub.)

Quoting from: http://www.gutenberg.org/wiki/Gutenberg:HTML_FAQ#H.4._What_are_the_PG_rules_for_HTML_texts.3F

>you should avoid: ...
>3. Forcing background colors other than white, or text colors other than black.

**Comment by eshellman** [comment]
It turns out that EbookMaker does NOT prevent producers from setting a background color. However, it loads its default stylesheet last, and that overrides the css that your page sets for <body>. This is not something we can change. Producers can use an enclosing div class  to set background color.
