### ISSUE TITLE
Version mismatch between PyPI.org and Github

### ISSUE THREAD

**Issue by jkoshy** [gutenbergtools/ebookmaker#62]
The version of ebookmaker at PyPI.org is v0.9.6 (please see https://pypi.org/project/ebookmaker/0.9.6/).

The current version in this repository is v0.9.5 (please see [gutenbergtools/ebookmaker/blob/master/ebookmaker/Version.py](https://github.com/gutenbergtools/ebookmaker/blob/master/ebookmaker/Version.py), commit hash da3a3110b759f94d02b86aadb9550ee88c5980ab).

I wanted to check if this repository is the primary development location for the project, or whether it has a  'more upstream' repository somewhere else?

**Comment by eshellman** [comment]
0.9.6 is on the cleanup branch - sometimes I don't merge my PRs right away. And there's some more cleanup to do!

**Comment by jkoshy** [comment]
Thank you for the clarification.

I'm not sure if making a public release from a cleanup branch would be a good practice.

For one, it makes it harder for external observers to rule out malicious activity.  A release which is not seen on the project's `master` branch could well be mistaken for a malicious one uploaded by a bad actor with access to the developer's credentials at PyPI.org.

Next, the `cleanup` branch in this repository would now need to be kept around indefinitely.  If the branch were ever to be deleted, the specific state of the source tree corresponding to the 0.9.6 release would become unreachable.  (I think you can remedy this situation by adding a tag, post-facto).

But more importantly, it confuses potential contributors.  If someone is looking at fixing an open issue with ebookmaker (say), it would not be obvious to them that the `cleanup` (or other) branch is the one that they should base their changes on.  They would start with 'master'—which risks duplicated work, possible difficulties during merging, and increased developer frustration.

I would say that smaller changes like code cleanups and refactorings are perfectly fine on `master`.

The general convention is also to use (git) tags to mark the state of the source tree corresponding to external releases, and to cut releases from long-lived branches.

**Comment by eshellman** [comment]
Understood. I try to always work on non-master branches, and modify master only via pull requests. I try to use master to represent what's in production; there's been an unusual delay in putting 0.9.6 into production. Ebookmaker runs on 3 production systems, and we can only deploy publicly released versions (with published source) to the production systems. Last year we had to do a lot of testing on a release from the development branch while continuing to support and modify the master branch.

I agree that tagging releases would be a good practice, I will do that going forward.
