### ISSUE TITLE
HTML <title> element holds a file name, as of v0.9.7

### ISSUE THREAD

**Issue by jkoshy** [gutenbergtools/ebookmaker#64]
As of v0.9.7 of `ebookmaker`:

```
% ebookmaker --version
EbookMaker 0.9.7

# Use ebook 63231 for the test.
% fgrep PG.Id cii.rst
   :PG.Id:       63231

# Run ebookmaker
% ebookmaker --make html --output-dir=/tmp/PG cii.rst

# The title in the generated HTML file contains the filename, instead of the value of the PG.Title field.
% fgrep '<title>' /tmp/PG/63231-h.html
<title>cii.rst</title>
```

Version 0.9.6 did not have this issue.

**Comment by eshellman** [comment]
I cannot reproduce that 0.9.6 and 0.9.7 are different in this respect. It's unlikely to have changed behavior in the past year. IIRC, <title> comes from:

- `--title` 
- the database if present
- the filename otherwise. 

You may see different content from the online ebookmaker because it's connected to the PG database.

**Comment by jkoshy** [comment]
The help message seems to say that the title comes from metadata if not explicitly specified:

```
% ebookmaker --help
...
  --title TITLE         ebook title (default: from meta)
...
```

The HTML `<title>` element should probably use the value of the `:DC.Title:` metadata field, defaulting to "No Title" if that field is not present.

This would be similar to the way output filenames are generated.  These use:

1. The value of the `:PG.Id:` field, if present,
2. Otherwise, the value of the `:DC.Title:` field, if present,
3. Otherwise, the string `"No title".

```
% ebookmaker --make html --output-dir=/tmp/PG cii.rst
% ls /tmp/PG
63231-h.html  63231-noimages-h.html   # File had the :PG.Id: field set.
```

**Comment by eshellman** [comment]
I'm rather unfamiliar with the rst processing; I think changing this would be correct. The database title should take precedence I think. in production, titles get normalized by cataloguers though an app that talks to the database - only the initial entry gets set by the submitted file.

**Comment by eshellman** [comment]
handling of --title has been clarified in #101
