### ISSUE TITLE
Kindlegen errors

### ISSUE THREAD

**Issue by 70ray** [gutenbergtools/ebookmaker#67]
Using 'x-ebookmaker'. No mobi files are generated and output.txt says 
```
unzipping /htdocs/ebookmaker/cache/20200928004919/mbuch.zip
Input file: mbuch.html
EbookMaker 0.9.7
...
ERROR:root:kindlegen: E21018: Enhanced Mobi building failure, while parsing content in the file. Content: <img> in file: /tmp/mobi-eAB2CX/10017/@htdocs@ebookmaker@cache@20200928004919@mbuch-1.html.html line: 13
ERROR:root:kindlegen: E21018: Enhanced Mobi building failure, while parsing content in the file. Content: <Vom tapfern Schneide> in file: /tmp/mobi-12QOh9/10017/@htdocs@ebookmaker@cache@20200928004919@mbuch-1.html.html line: 16
```

epub seems to be generated correctly.

**Comment by 70ray** [comment]
In the html file which caused the problem an image with class "a0" was excluded from ebook by the statement:
```
.x-ebookmaker img.a0 {
    display: none;
}
```
If instead it is excluded by omitting that statement and giving it the additional class "x-ebookmaker-drop" then the operation succeeds.
Does this mean that "display: none" should never be used in a ".x-ebookmaker" class definition?

**Comment by eshellman** [comment]
`display: none` reliably causes kindlegen to fail when the hidden content is the target of an internal link. I don't think it has anything to do with .x-ebookmaker. Note that h1, h2 elements, etc are used as targets for internal links by the code that generates a table of contents, so these should never have `display: none` applied to them.

**Comment by eshellman** [comment]
possibl `display: none` will cause conversion failures if used on img elements.
