### ISSUE TITLE
Kobo has trouble displaying license text at end of epub

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/ebookmaker#73]
This was reported to the Project Gutenberg helpdesk, and I've replicated on my Kobo with this one: https://www.gutenberg.org/ebooks/1661 (I picked it because it's in our top-10 downloads).

What happens is: when reading to the end of the book, after the last chapter, the small print license text starts. The Kobo suddenly gets very slow, taking minutes to advance to the next page and seeming like it's hung or crashed. I eventually managed to get to the end of the file, after patiently swiping for 15 minutes or so.

The only other thing I noticed is that page numbers became incorrect. The page count in the footer on the Kobo (i.e., the Kobo's count, not the page numbers in the epub) was a few less than were actually there. I.e., it said something like p. 241 or 248, and p. 13 of 20 in the chapter, but actually there were three or four more pages beyond #248 and p. 20.

If you suggest an alternate book to look at, or a pre-release built version, I can try again. Kobo is, generally, pretty friendly towards PG eBooks: just connect the device via USB, the drag-and-drop from computer to Kobo.

**Comment by eshellman** [comment]
Kobo must have difficulty paginating the monospaced font. Issue most likely will go away with the new headers, but might be worth reporting to Kobo as a bug. I bet the issue also goes away if you make the type size small enough so each line fits on a line.

**Comment by gbnewby** [comment]
Roger did some investigation, and saw that the footer is one long line. He
made a new version that I will test later. Indeed, the new footer will
probably help (even if the problem is something different than one long
line).

**Comment by eshellman** [comment]
That's definitely the issue. Way to go @asylumcs !
