### ISSUE TITLE
Chapter headings beginning with "by" are omitted from generated ToC

### ISSUE THREAD

**Issue by windymilla** [gutenbergtools/ebookmaker#75]
In an attempt to avoid adding the author's name as an entry in the generated ToC, due to the historical practice of wrapping the title in h1 markup and "By author" in h2 or h3 markup, the code [here](https://github.com/gutenbergtools/ebookmaker/blob/c114aa791d2d585fa5c53f42e59a3b2ff1cd60a4/ebookmaker/parsers/__init__.py#L499) does not add genuine chapter titles that begin with "By".

Reported at DP [here](https://www.pgdp.net/phpBB3/viewtopic.php?f=3&t=41237&p=1233937#p1233929)

**Comment by windymilla** [comment]
Fixing this might break some old books, i.e. they might get "By Will Shakespeare" as an apparent chapter title.

**Comment by susanskinner** [comment]
The DP project that I spotted this in is a periodical and the problem <h2> is the first installment of a weekly serialised story which continues for at least the next 30 weekly issues. I expect the number of older projects with incorrect <h2> usage is much larger than that but this does affect a not insignificant number of upcoming projects.

**Comment by eshellman** [comment]
@susanskinner I suggest you add the 'x-ebookmaker-important' class to the heading element and we'll add a line of code to override the existing behavior without breaking anything in the backfile.

**Comment by susanskinner** [comment]
Perfect - I will do that, thanks!

**Comment by windymilla** [comment]
@eshellman - that means that all backfile chapter headings that genuinely start with "By " and all similar future submissions from anyone who doesn't know about the x-ebookmaker-important class will have the same problem. It is the sort of thing that could easily go unnoticed by a PPer or the WWer when it is submitted. My personal view is that it would be better to have some old files that appear to have a dummy chapter "By Will Shakespeare" in their ToC than for books to have a chapter omitted.
I don't know if you or @asylumcs know how many old books it affects, or how much work it would be to replace the 'h2' with a suitably styled 'p' or 'div' in those books that use h2 for their author.

**Comment by eshellman** [comment]
I can also add code that logs omitted headings so that we can see how many books are affected.

**Comment by windymilla** [comment]
I'm sure that would be helpful in determining the best solution.

**Comment by asylumcs** [comment]
"I don't know if you or @asylumcs know how many old books it affects, or how much work it would be to replace the 'h2' with a suitably styled 'p' or 'div' in those books that use h2 for their author."

I am happy scan the catalog if it would help. I'm not sure exactly the pattern. Is it only h2's that start with the word "by"? Are we assuming only h2 tags are chapters or that all h2 tags are chapters? You don't want me to report "<h1 class='nobreak'>By the Good Sainte Anne</h1>" as in 60175, right?

**Comment by asylumcs** [comment]
Scan summary.

examples:
36705-h.htm:<h1>BY RIGHT OF PURCHASE</h1>
49748-h.htm:<h2>BY THE FADING LIGHT.</h2>
49936-h.htm:<h3>By Sinking a Wooden Tank</h3>
37546-h.htm:<h4 class="spaced">By Her MAJESTY'S Servants.</h4>

Counts of "By " used in headers:
  h1: 48 occurrences 
  h2: 3820
  h3: 5946
  h4: 1984

I haven't scanned for the title field yet. On the road; I'll do that tonight, motel wifi permitting.

**Comment by eshellman** [comment]
@susanskinner we can override the heading omission please don't use <h*> tags control type size; this results in a terrible toc in the ebook and reflects poorly on PG. Mistakes like that are the reason ebookmaker has hacks such as the one we need to override here.

**Comment by eshellman** [comment]
@susanskinner We could also introduce a class that suppressed the use of a heading for the TOC, if we felt that DPers would use it:` x-ebookmaker-nohead` but it would be easier if we could just get DPer's not to mis-use `<h*>` tags. What does the best practices document say?

**Comment by windymilla** [comment]
@eshellman - you may have misunderstood, @susanskinner is not trying to use h* tags to control size. She is using them for their proper purpose - a chapter heading, but in this book, the chapter heading is "By Mead and Stream". She is a victim of the ebookmaker hack, not a contributor to it.
The best practices document makes it clear that h* are only to be used for headings, and that the outline of the book as described by the HTML headings (e.g. chapters, sections, etc.) should reflect the outline of the book as described in the printed ToC if there is one.
The practice of using h* tags for size has been deprecated at DP for many years, and I'm sure all recently trained PPers at DP use them correctly. I suspect the books turned up by Roger's search will mostly be either old, or not from DP, or perhaps from an old PPer at DP who hasn't yet changed their ways.

**Comment by eshellman** [comment]
@windymilla 60175 is not an "old" book. I misunderstood that it was the one @susanskinner was working on. Sorry!

**Comment by windymilla** [comment]
That's right - it comes under my category of "not from DP"
