### ISSUE TITLE
Support for svg files

### ISSUE THREAD

**Issue by 70ray** [gutenbergtools/ebookmaker#8]
svg in html should be ok. For epub, newer versions should support svg but older ereaders don't so ideally we would need an option to specify different ereader versions with the older ones having svg converted to png.

**Comment by 70ray** [comment]
I had thought this would be easy -- I was wrong.
The test file I used was made by dvisvgm


Cairosvg was troublesome to install on windows and results were no use.

**Comment by 70ray** [comment]
Accidentaly pressed the close and comment button -- start again --
I had thought this would be easy -- I was wrong.

Cairosvg was troublesome to install on windows and results were no use.
ImageMagick was no good either.
Inkscape was quite good but the primes in the image were too high (Edge also has this problem, but IE11 is OK)
I found two which used Chromium which were promising:
[https://github.com/domenic/svg2png](url) had the same prime problem.
[https://github.com/neocotic/convert-svg](url) gives a good image but the bottom was clipped unless you specify a height parameter in the command line. I'll report this issue to the author.
This is the test file I used:
[ba585957575f9f4b5b190bbd92b13b9c.zip](https://github.com/gutenbergtools/ebookmaker/files/2821036/ba585957575f9f4b5b190bbd92b13b9c.zip)

**Comment by eshellman** [comment]
Thanks for looking into this. Worth revisiting in the future.

**Comment by wf49670** [comment]
I found this conversation a bit confusing, in part because it does not provide any justification for needing or including svg support. Wouldn't a use case and/or user requirements be a good starting point for including such support?

**Comment by 70ray** [comment]
> 
> 
> I found this conversation a bit confusing, in part because it does not provide any justification for needing or including svg support. Wouldn't a use case and/or user requirements be a good starting point for including such support?

Good point. It was motivated by the experiment I was doing on embedding images for math expressions encoded in LaTex into a book, although it could apply also to other sorts of images. Svg images have the advantage that you can zoom in without losing sharpness. This would be good for html and although the newer specifications for epub include svg, png would still be needed to support older ereaders. It would then seem best to provide just one master set of svg images to PG for such a book and for them to be converted to png to make an epub version.

**Comment by eshellman** [comment]
I'm assuming the mathjax solutions are the ones to emulate.

**Comment by 70ray** [comment]
Yes, in the sense that starting with basically an html document with embedded maths in Latex you could either view it with MathJax or convert the maths to images.
Since we already have the means to convert the LaTex to either png or svg images (see [https://www.pgdp.net/wiki/User:RP31/Math_conversion_tool](url)), in a way it would be logical to treat the html+LaTex as the master document and make svg or png images as required which would avoid any need to convert svg to png. But would this be acceptable to PG?

**Comment by eshellman** [comment]
is that new? where did it come from? ebookmaker doesn't allow px?

**Comment by wf49670** [comment]
On 2/4/2019 12:11 PM, Ray Papworth wrote:
>
> Yes, in the sense that starting with basically an html document with 
> embedded maths in Latex you could either view it with MathJax or 
> convert the maths to images.
> Since we already have the means to convert the LaTex to either png or 
> svg images (see 
> https://www.pgdp.net/wiki/User:RP31/Math_conversion_tool <url>), in a 
> way it would be logical to treat the html+LaTex as the master document 
> and make svg or png images as required which would avoid any need to 
> convert svg to png. But would this be acceptable to PG?
>
As far as I know PG does not allow HTML+LaTeX. They will accept a LaTeX 
file and generate a PDF, but the mixture you mention does not fit into 
the toolchain the WWers use.

-- 
Walt

**Comment by eshellman** [comment]
by HTML+LaTeX, do you mean mathjax-style  markup in script tags: <script type="math/tex">x+\sqrt{1-x^2}</script> ?

**Comment by 70ray** [comment]
> 
> 
> is that new? where did it come from? ebookmaker doesn't allow px?

It's in 
ebookmaker/writers/EpubWriter.py line 848
so it would only apply to epubs but it would have to be worked round for everything. I gues it is meant to catch something undesirable but catches other thing also.

**Comment by 70ray** [comment]
> 
> On 2/4/2019 12:11 PM, Ray Papworth wrote: Yes, in the sense that starting with basically an html document with embedded maths in Latex you could either view it with MathJax or convert the maths to images. Since we already have the means to convert the LaTex to either png or svg images (see https://www.pgdp.net/wiki/User:RP31/Math_conversion_tool <url>), in a way it would be logical to treat the html+LaTex as the master document and make svg or png images as required which would avoid any need to convert svg to png. But would this be acceptable to PG?
> As far as I know PG does not allow HTML+LaTeX. They will accept a LaTeX file and generate a PDF, but the mixture you mention does not fit into the toolchain the WWers use.
> […](#)
> -- Walt

Do you think there could be a way to proceed?

**Comment by 70ray** [comment]
> 
> 
> by HTML+LaTeX, do you mean mathjax-style markup in script tags: <script type="math/tex">x+\sqrt{1-x^2}</script> ?

I was just using the LaTex delimiters \[...\] and \(...\) rather than script tags but the same sort of thing.

**Comment by eshellman** [comment]
I guess px is not allowed because it's expected that the user will change font size and so all spacing should be in ems and exs or %, but why are pt and mm allowed?

**Comment by eshellman** [comment]
fixed in 0.10.1
