### ISSUE TITLE
Creation of meaningless links "back" when additional images are linked

### ISSUE THREAD

**Issue by xwodas** [gutenbergtools/ebookmaker#82]
I have a book with links to additional larger-size images. The links are dropped in EPUB via the x-ebookmaker-drop mechanism and the images are not added to the EPUB. Instead, there are additional HTML documents piled up at the end of the book with the text "linked image" and a meaningless link "back" to the first HTML in the EPUB as the only content, one for each of the removed images. These HTML documents have the names of the removed images in their file names, so there is a clear connection.

I attach a zip file as it was used for ebookmaker in this eaxample.
[bla.zip](https://github.com/gutenbergtools/ebookmaker/files/6543621/bla.zip)

**Comment by eshellman** [comment]
You shouldn't drop these links. As you have observed this results in much badness.

You can use the rel=nofollow type link instead.

**Comment by eshellman** [comment]
addressed by #83
