### ISSUE TITLE
<q> tag handling incorrect

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#85]
Most of the <q> tag handling modifications are working correctly. Thank you. This is the only failing case I found that we might see from an uploader.

source HTML: <q style='font-style:italic'>Dynamite!</q>
Ebookmaker rewrite: <span class="c4">“Dynamite!”</span>
where 'c4' is defined in 1.css as q.c4 { font-style: italic }

The problem is that c4 will only apply to q tags, which don't exist. Perhaps it should be "span.c4" and not "q.c4" in 1.css. Thanks.

**Comment by eshellman** [comment]
fixed for EPUB3. Won't fix for EPUB2
