### ISSUE TITLE
RST is disallowed

### ISSUE THREAD

**Issue by asylumcs** [gutenbergtools/ebookmaker#87]
RST uploads are no longer accepted at Project Gutenberg. On the https://epubmaker.pglaf.org/ page, there are at least seven references to RST that should be removed.

**Comment by jkoshy** [comment]
FYI, the https://epubmaker.pglaf.org/ page has been fixed.

**Comment by eshellman** [comment]
not really an ebookmaker issue, except that enhancements (as opposed to bug fixes) will no longer be accepted.
